package com.haak.haaksq.form;

// Generated Jun 29, 2012 11:08:03 PM by Hibernate Tools 3.4.0.CR1

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private int addressId;
	private String addressNo;
	private String soi;
	private String moo;
	private String road;
	private String tumbol;
	private String amphoe;
	private String city;
	private String state;
	private String zipcode;
	private String country;
	private String telephone;
	private String mobile;

	public Address() {
	}

	public Address(int addressId) {
		this.addressId = addressId;
	}

	public Address(int addressId, String addressNo, String soi, String moo,
			String road, String tumbol, String amphoe, String city,
			String state, String zipcode, String country, String telephone,
			String mobile) {
		this.addressId = addressId;
		this.addressNo = addressNo;
		this.soi = soi;
		this.moo = moo;
		this.road = road;
		this.tumbol = tumbol;
		this.amphoe = amphoe;
		this.city = city;
		this.state = state;
		this.zipcode = zipcode;
		this.country = country;
		this.telephone = telephone;
		this.mobile = mobile;
	}

	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	public String getAddressNo() {
		return this.addressNo;
	}

	public void setAddressNo(String addressNo) {
		this.addressNo = addressNo;
	}

	public String getSoi() {
		return this.soi;
	}

	public void setSoi(String soi) {
		this.soi = soi;
	}

	public String getMoo() {
		return this.moo;
	}

	public void setMoo(String moo) {
		this.moo = moo;
	}

	public String getRoad() {
		return this.road;
	}

	public void setRoad(String road) {
		this.road = road;
	}

	public String getTumbol() {
		return this.tumbol;
	}

	public void setTumbol(String tumbol) {
		this.tumbol = tumbol;
	}

	public String getAmphoe() {
		return this.amphoe;
	}

	public void setAmphoe(String amphoe) {
		this.amphoe = amphoe;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

}
