package com.haak.haaksq.form;

// Generated 10 �.�. 2555, 19:52:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstLiftstyleType generated by hbm2java
 */
@Entity
@Table(name = "mst_liftstyle_type", catalog = "haaksquare_db")
public class MstLiftstyleType implements java.io.Serializable {

	private int lifestyleTypeId;
	private Integer languageId;
	private Integer lifestyleId;
	private String lifestyleTypeName;
	private Integer modifyBy;
	private Date modifyDate;
	private Integer createBy;
	private Date createDate;

	public MstLiftstyleType() {
	}

	public MstLiftstyleType(int lifestyleTypeId) {
		this.lifestyleTypeId = lifestyleTypeId;
	}

	public MstLiftstyleType(int lifestyleTypeId, Integer languageId,
			Integer lifestyleId, String lifestyleTypeName, Integer modifyBy,
			Date modifyDate, Integer createBy, Date createDate) {
		this.lifestyleTypeId = lifestyleTypeId;
		this.languageId = languageId;
		this.lifestyleId = lifestyleId;
		this.lifestyleTypeName = lifestyleTypeName;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "lifestyle_type_id", unique = true, nullable = false)
	public int getLifestyleTypeId() {
		return this.lifestyleTypeId;
	}

	public void setLifestyleTypeId(int lifestyleTypeId) {
		this.lifestyleTypeId = lifestyleTypeId;
	}

	@Column(name = "language_id")
	public Integer getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(Integer languageId) {
		this.languageId = languageId;
	}

	@Column(name = "lifestyle_id")
	public Integer getLifestyleId() {
		return this.lifestyleId;
	}

	public void setLifestyleId(Integer lifestyleId) {
		this.lifestyleId = lifestyleId;
	}

	@Column(name = "lifestyle_type_name")
	public String getLifestyleTypeName() {
		return this.lifestyleTypeName;
	}

	public void setLifestyleTypeName(String lifestyleTypeName) {
		this.lifestyleTypeName = lifestyleTypeName;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
