package com.haak.haaksq.form;

// Generated Feb 11, 2013 7:23:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StmImg generated by hbm2java
 */
@Entity
@Table(name = "stm_img", catalog = "haaksquare_db")
public class StmImg implements java.io.Serializable {

	private Integer id;
	private String imgPath;
	private String imgName;
	private Integer createBy;
	private String ipAddress;
	private Date createDate;
	private String flagRecord;

	public StmImg() {
	}

	public StmImg(String imgPath, String imgName, Integer createBy,
			String ipAddress, Date createDate, String flagRecord) {
		this.imgPath = imgPath;
		this.imgName = imgName;
		this.createBy = createBy;
		this.ipAddress = ipAddress;
		this.createDate = createDate;
		this.flagRecord = flagRecord;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "img_path", length = 200)
	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	@Column(name = "img_name", length = 200)
	public String getImgName() {
		return this.imgName;
	}

	public void setImgName(String imgName) {
		this.imgName = imgName;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Column(name = "ip_address", length = 20)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "flag_record", length = 1)
	public String getFlagRecord() {
		return this.flagRecord;
	}

	public void setFlagRecord(String flagRecord) {
		this.flagRecord = flagRecord;
	}

}
