package com.haak.haaksq.form;

// Generated Jul 23, 2012 11:44:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * VBoardStructure generated by hbm2java
 */
public class VBoardStructure implements java.io.Serializable {

	private VBoardStructureId id;

	public VBoardStructure() {
	}

	public VBoardStructure(VBoardStructureId id) {
		this.id = id;
	}

	public VBoardStructureId getId() {
		return this.id;
	}

	public void setId(VBoardStructureId id) {
		this.id = id;
	}

}
