package com.haak.haaksq.form;

// Generated May 29, 2012 11:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * VCommunitySaleRentId generated by hbm2java
 */
public class VCommunitySaleRentId implements java.io.Serializable {

	private int communitySaleRentId;
	private int communityId;
	private String salesRentName;
	private String communityTypeName;
	private Long valueAmount;
	private Long landSpace;
	private Long liveSpace;
	private Integer bedRoom;
	private Integer bathRoom;
	private String salesRentDetail;
	private String exteriorOption;
	private String interiorOption;
	private String contract;
	private String fileName;
	private String pathName;
	private String attachUrl;
	private String salesRentUrl;
	private int attachSeq;
	private String fileDetail;
	private int languageId;

	public VCommunitySaleRentId() {
	}

	public VCommunitySaleRentId(int communitySaleRentId, int communityId,
			String fileName, String pathName, String attachUrl, int attachSeq,
			String fileDetail, int languageId) {
		this.communitySaleRentId = communitySaleRentId;
		this.communityId = communityId;
		this.fileName = fileName;
		this.pathName = pathName;
		this.attachUrl = attachUrl;
		this.attachSeq = attachSeq;
		this.fileDetail = fileDetail;
		this.languageId = languageId;
	}

	public VCommunitySaleRentId(int communitySaleRentId, int communityId,
			String salesRentName, String communityTypeName, Long valueAmount,
			Long landSpace, Long liveSpace, Integer bedRoom, Integer bathRoom,
			String salesRentDetail, String exteriorOption,
			String interiorOption, String contract, String fileName,
			String pathName, String attachUrl, String salesRentUrl,
			int attachSeq, String fileDetail, int languageId) {
		this.communitySaleRentId = communitySaleRentId;
		this.communityId = communityId;
		this.salesRentName = salesRentName;
		this.communityTypeName = communityTypeName;
		this.valueAmount = valueAmount;
		this.landSpace = landSpace;
		this.liveSpace = liveSpace;
		this.bedRoom = bedRoom;
		this.bathRoom = bathRoom;
		this.salesRentDetail = salesRentDetail;
		this.exteriorOption = exteriorOption;
		this.interiorOption = interiorOption;
		this.contract = contract;
		this.fileName = fileName;
		this.pathName = pathName;
		this.attachUrl = attachUrl;
		this.salesRentUrl = salesRentUrl;
		this.attachSeq = attachSeq;
		this.fileDetail = fileDetail;
		this.languageId = languageId;
	}

	public int getCommunitySaleRentId() {
		return this.communitySaleRentId;
	}

	public void setCommunitySaleRentId(int communitySaleRentId) {
		this.communitySaleRentId = communitySaleRentId;
	}

	public int getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(int communityId) {
		this.communityId = communityId;
	}

	public String getSalesRentName() {
		return this.salesRentName;
	}

	public void setSalesRentName(String salesRentName) {
		this.salesRentName = salesRentName;
	}

	public String getCommunityTypeName() {
		return this.communityTypeName;
	}

	public void setCommunityTypeName(String communityTypeName) {
		this.communityTypeName = communityTypeName;
	}

	public Long getValueAmount() {
		return this.valueAmount;
	}

	public void setValueAmount(Long valueAmount) {
		this.valueAmount = valueAmount;
	}

	public Long getLandSpace() {
		return this.landSpace;
	}

	public void setLandSpace(Long landSpace) {
		this.landSpace = landSpace;
	}

	public Long getLiveSpace() {
		return this.liveSpace;
	}

	public void setLiveSpace(Long liveSpace) {
		this.liveSpace = liveSpace;
	}

	public Integer getBedRoom() {
		return this.bedRoom;
	}

	public void setBedRoom(Integer bedRoom) {
		this.bedRoom = bedRoom;
	}

	public Integer getBathRoom() {
		return this.bathRoom;
	}

	public void setBathRoom(Integer bathRoom) {
		this.bathRoom = bathRoom;
	}

	public String getSalesRentDetail() {
		return this.salesRentDetail;
	}

	public void setSalesRentDetail(String salesRentDetail) {
		this.salesRentDetail = salesRentDetail;
	}

	public String getExteriorOption() {
		return this.exteriorOption;
	}

	public void setExteriorOption(String exteriorOption) {
		this.exteriorOption = exteriorOption;
	}

	public String getInteriorOption() {
		return this.interiorOption;
	}

	public void setInteriorOption(String interiorOption) {
		this.interiorOption = interiorOption;
	}

	public String getContract() {
		return this.contract;
	}

	public void setContract(String contract) {
		this.contract = contract;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getPathName() {
		return this.pathName;
	}

	public void setPathName(String pathName) {
		this.pathName = pathName;
	}

	public String getAttachUrl() {
		return this.attachUrl;
	}

	public void setAttachUrl(String attachUrl) {
		this.attachUrl = attachUrl;
	}

	public String getSalesRentUrl() {
		return this.salesRentUrl;
	}

	public void setSalesRentUrl(String salesRentUrl) {
		this.salesRentUrl = salesRentUrl;
	}

	public int getAttachSeq() {
		return this.attachSeq;
	}

	public void setAttachSeq(int attachSeq) {
		this.attachSeq = attachSeq;
	}

	public String getFileDetail() {
		return this.fileDetail;
	}

	public void setFileDetail(String fileDetail) {
		this.fileDetail = fileDetail;
	}

	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VCommunitySaleRentId))
			return false;
		VCommunitySaleRentId castOther = (VCommunitySaleRentId) other;

		return (this.getCommunitySaleRentId() == castOther
				.getCommunitySaleRentId())
				&& (this.getCommunityId() == castOther.getCommunityId())
				&& ((this.getSalesRentName() == castOther.getSalesRentName()) || (this
						.getSalesRentName() != null
						&& castOther.getSalesRentName() != null && this
						.getSalesRentName()
						.equals(castOther.getSalesRentName())))
				&& ((this.getCommunityTypeName() == castOther
						.getCommunityTypeName()) || (this
						.getCommunityTypeName() != null
						&& castOther.getCommunityTypeName() != null && this
						.getCommunityTypeName().equals(
								castOther.getCommunityTypeName())))
				&& ((this.getValueAmount() == castOther.getValueAmount()) || (this
						.getValueAmount() != null
						&& castOther.getValueAmount() != null && this
						.getValueAmount().equals(castOther.getValueAmount())))
				&& ((this.getLandSpace() == castOther.getLandSpace()) || (this
						.getLandSpace() != null
						&& castOther.getLandSpace() != null && this
						.getLandSpace().equals(castOther.getLandSpace())))
				&& ((this.getLiveSpace() == castOther.getLiveSpace()) || (this
						.getLiveSpace() != null
						&& castOther.getLiveSpace() != null && this
						.getLiveSpace().equals(castOther.getLiveSpace())))
				&& ((this.getBedRoom() == castOther.getBedRoom()) || (this
						.getBedRoom() != null && castOther.getBedRoom() != null && this
						.getBedRoom().equals(castOther.getBedRoom())))
				&& ((this.getBathRoom() == castOther.getBathRoom()) || (this
						.getBathRoom() != null
						&& castOther.getBathRoom() != null && this
						.getBathRoom().equals(castOther.getBathRoom())))
				&& ((this.getSalesRentDetail() == castOther
						.getSalesRentDetail()) || (this.getSalesRentDetail() != null
						&& castOther.getSalesRentDetail() != null && this
						.getSalesRentDetail().equals(
								castOther.getSalesRentDetail())))
				&& ((this.getExteriorOption() == castOther.getExteriorOption()) || (this
						.getExteriorOption() != null
						&& castOther.getExteriorOption() != null && this
						.getExteriorOption().equals(
								castOther.getExteriorOption())))
				&& ((this.getInteriorOption() == castOther.getInteriorOption()) || (this
						.getInteriorOption() != null
						&& castOther.getInteriorOption() != null && this
						.getInteriorOption().equals(
								castOther.getInteriorOption())))
				&& ((this.getContract() == castOther.getContract()) || (this
						.getContract() != null
						&& castOther.getContract() != null && this
						.getContract().equals(castOther.getContract())))
				&& ((this.getFileName() == castOther.getFileName()) || (this
						.getFileName() != null
						&& castOther.getFileName() != null && this
						.getFileName().equals(castOther.getFileName())))
				&& ((this.getPathName() == castOther.getPathName()) || (this
						.getPathName() != null
						&& castOther.getPathName() != null && this
						.getPathName().equals(castOther.getPathName())))
				&& ((this.getAttachUrl() == castOther.getAttachUrl()) || (this
						.getAttachUrl() != null
						&& castOther.getAttachUrl() != null && this
						.getAttachUrl().equals(castOther.getAttachUrl())))
				&& ((this.getSalesRentUrl() == castOther.getSalesRentUrl()) || (this
						.getSalesRentUrl() != null
						&& castOther.getSalesRentUrl() != null && this
						.getSalesRentUrl().equals(castOther.getSalesRentUrl())))
				&& (this.getAttachSeq() == castOther.getAttachSeq())
				&& ((this.getFileDetail() == castOther.getFileDetail()) || (this
						.getFileDetail() != null
						&& castOther.getFileDetail() != null && this
						.getFileDetail().equals(castOther.getFileDetail())))
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCommunitySaleRentId();
		result = 37 * result + this.getCommunityId();
		result = 37
				* result
				+ (getSalesRentName() == null ? 0 : this.getSalesRentName()
						.hashCode());
		result = 37
				* result
				+ (getCommunityTypeName() == null ? 0 : this
						.getCommunityTypeName().hashCode());
		result = 37
				* result
				+ (getValueAmount() == null ? 0 : this.getValueAmount()
						.hashCode());
		result = 37 * result
				+ (getLandSpace() == null ? 0 : this.getLandSpace().hashCode());
		result = 37 * result
				+ (getLiveSpace() == null ? 0 : this.getLiveSpace().hashCode());
		result = 37 * result
				+ (getBedRoom() == null ? 0 : this.getBedRoom().hashCode());
		result = 37 * result
				+ (getBathRoom() == null ? 0 : this.getBathRoom().hashCode());
		result = 37
				* result
				+ (getSalesRentDetail() == null ? 0 : this.getSalesRentDetail()
						.hashCode());
		result = 37
				* result
				+ (getExteriorOption() == null ? 0 : this.getExteriorOption()
						.hashCode());
		result = 37
				* result
				+ (getInteriorOption() == null ? 0 : this.getInteriorOption()
						.hashCode());
		result = 37 * result
				+ (getContract() == null ? 0 : this.getContract().hashCode());
		result = 37 * result
				+ (getFileName() == null ? 0 : this.getFileName().hashCode());
		result = 37 * result
				+ (getPathName() == null ? 0 : this.getPathName().hashCode());
		result = 37 * result
				+ (getAttachUrl() == null ? 0 : this.getAttachUrl().hashCode());
		result = 37
				* result
				+ (getSalesRentUrl() == null ? 0 : this.getSalesRentUrl()
						.hashCode());
		result = 37 * result + this.getAttachSeq();
		result = 37
				* result
				+ (getFileDetail() == null ? 0 : this.getFileDetail()
						.hashCode());
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
