package com.haak.haaksq.form;


// Generated Jun 28, 2012 10:58:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * VCommunityNews generated by hbm2java
 */
public class VCommunityNews implements java.io.Serializable {

	private VCommunityNewsId id;

	public VCommunityNews() {
	}

	public VCommunityNews(VCommunityNewsId id) {
		this.id = id;
	}

	public VCommunityNewsId getId() {
		return this.id;
	}

	public void setId(VCommunityNewsId id) {
		this.id = id;
	}

}
