package com.haak.haaksq.form;

// Generated May 24, 2012 11:55:11 PM by Hibernate Tools 3.4.0.CR1

/**
 * VCommunityGallary generated by hbm2java
 */
public class VCommunityGallary implements java.io.Serializable {

	private VCommunityGallaryId id;

	public VCommunityGallary() {
	}

	public VCommunityGallary(VCommunityGallaryId id) {
		this.id = id;
	}

	public VCommunityGallaryId getId() {
		return this.id;
	}

	public void setId(VCommunityGallaryId id) {
		this.id = id;
	}

}
