package com.haak.haaksq.form;

// Generated May 24, 2012 11:45:24 PM by Hibernate Tools 3.4.0.CR1

/**
 * VCommunityDetail generated by hbm2java
 */
public class VCommunityDetail implements java.io.Serializable {

	private VCommunityDetailId id;

	public VCommunityDetail() {
	}

	public VCommunityDetail(VCommunityDetailId id) {
		this.id = id;
	}

	public VCommunityDetailId getId() {
		return this.id;
	}

	public void setId(VCommunityDetailId id) {
		this.id = id;
	}

}
