package com.haak.haaksq.form;

// Generated May 29, 2012 11:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * VCommunityLifestylePicture generated by hbm2java
 */
public class VCommunityLifestylePicture implements java.io.Serializable {

	private VCommunityLifestylePictureId id;

	public VCommunityLifestylePicture() {
	}

	public VCommunityLifestylePicture(VCommunityLifestylePictureId id) {
		this.id = id;
	}

	public VCommunityLifestylePictureId getId() {
		return this.id;
	}

	public void setId(VCommunityLifestylePictureId id) {
		this.id = id;
	}

}
