package com.haak.haaksq.form;

// Generated May 29, 2012 11:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * VCommunitySaleRent generated by hbm2java
 */
public class VCommunitySaleRent implements java.io.Serializable {

	private VCommunitySaleRentId id;

	public VCommunitySaleRent() {
	}

	public VCommunitySaleRent(VCommunitySaleRentId id) {
		this.id = id;
	}

	public VCommunitySaleRentId getId() {
		return this.id;
	}

	public void setId(VCommunitySaleRentId id) {
		this.id = id;
	}

}
