package com.haak.haaksq.form;

// Generated Sep 26, 2012 11:53:40 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * VCommunityWhatNearById generated by hbm2java
 */
public class VCommunityWhatNearBy implements java.io.Serializable {

	private int communityLifestyleId;
	private int communityId;
	private String lifestyleName;
	private String lifestyleTypeName;
	private String lifestyleFullName;
	private String lifestyleDetail;
	private BigDecimal distanceFromHoa;
	private String lifestyleLink;
	private String lifestyleUrl;
	private String lifestyleGoogleMap;
	private String googleMapLatitude;
	private String googleMapLongtitude;
	private String googleMapUrl;
	private String liftStyleUrl;
	private String lifeStyleGoogleMap;
	private Integer languageId;
	private String recommende;
	private String address;
	private String contractNo;

	public VCommunityWhatNearBy() {
	}

	public VCommunityWhatNearBy(int communityLifestyleId, int communityId) {
		this.communityLifestyleId = communityLifestyleId;
		this.communityId = communityId;
	}

	public VCommunityWhatNearBy(int communityLifestyleId, int communityId,
			String lifestyleName, String lifestyleTypeName,
			String lifestyleFullName, String lifestyleDetail,
			BigDecimal distanceFromHoa, String lifestyleLink,
			String lifestyleUrl, String lifestyleGoogleMap,
			String googleMapLatitude, String googleMapLongtitude,
			String googleMapUrl, String liftStyleUrl,
			String lifeStyleGoogleMap, Integer languageId, String recommende,
			String address, String contractNo) {
		this.communityLifestyleId = communityLifestyleId;
		this.communityId = communityId;
		this.lifestyleName = lifestyleName;
		this.lifestyleTypeName = lifestyleTypeName;
		this.lifestyleFullName = lifestyleFullName;
		this.lifestyleDetail = lifestyleDetail;
		this.distanceFromHoa = distanceFromHoa;
		this.lifestyleLink = lifestyleLink;
		this.lifestyleUrl = lifestyleUrl;
		this.lifestyleGoogleMap = lifestyleGoogleMap;
		this.googleMapLatitude = googleMapLatitude;
		this.googleMapLongtitude = googleMapLongtitude;
		this.googleMapUrl = googleMapUrl;
		this.liftStyleUrl = liftStyleUrl;
		this.lifeStyleGoogleMap = lifeStyleGoogleMap;
		this.languageId = languageId;
		this.recommende = recommende;
		this.address = address;
		this.contractNo = contractNo;
	}

	public int getCommunityLifestyleId() {
		return this.communityLifestyleId;
	}

	public void setCommunityLifestyleId(int communityLifestyleId) {
		this.communityLifestyleId = communityLifestyleId;
	}

	public int getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(int communityId) {
		this.communityId = communityId;
	}

	public String getLifestyleName() {
		return this.lifestyleName;
	}

	public void setLifestyleName(String lifestyleName) {
		this.lifestyleName = lifestyleName;
	}

	public String getLifestyleTypeName() {
		return this.lifestyleTypeName;
	}

	public void setLifestyleTypeName(String lifestyleTypeName) {
		this.lifestyleTypeName = lifestyleTypeName;
	}

	public String getLifestyleFullName() {
		return this.lifestyleFullName;
	}

	public void setLifestyleFullName(String lifestyleFullName) {
		this.lifestyleFullName = lifestyleFullName;
	}

	public String getLifestyleDetail() {
		return this.lifestyleDetail;
	}

	public void setLifestyleDetail(String lifestyleDetail) {
		this.lifestyleDetail = lifestyleDetail;
	}

	public BigDecimal getDistanceFromHoa() {
		return this.distanceFromHoa;
	}

	public void setDistanceFromHoa(BigDecimal distanceFromHoa) {
		this.distanceFromHoa = distanceFromHoa;
	}

	public String getLifestyleLink() {
		return this.lifestyleLink;
	}

	public void setLifestyleLink(String lifestyleLink) {
		this.lifestyleLink = lifestyleLink;
	}

	public String getLifestyleUrl() {
		return this.lifestyleUrl;
	}

	public void setLifestyleUrl(String lifestyleUrl) {
		this.lifestyleUrl = lifestyleUrl;
	}

	public String getLifestyleGoogleMap() {
		return this.lifestyleGoogleMap;
	}

	public void setLifestyleGoogleMap(String lifestyleGoogleMap) {
		this.lifestyleGoogleMap = lifestyleGoogleMap;
	}

	public String getGoogleMapLatitude() {
		return this.googleMapLatitude;
	}

	public void setGoogleMapLatitude(String googleMapLatitude) {
		this.googleMapLatitude = googleMapLatitude;
	}

	public String getGoogleMapLongtitude() {
		return this.googleMapLongtitude;
	}

	public void setGoogleMapLongtitude(String googleMapLongtitude) {
		this.googleMapLongtitude = googleMapLongtitude;
	}

	public String getGoogleMapUrl() {
		return this.googleMapUrl;
	}

	public void setGoogleMapUrl(String googleMapUrl) {
		this.googleMapUrl = googleMapUrl;
	}

	public String getLiftStyleUrl() {
		return this.liftStyleUrl;
	}

	public void setLiftStyleUrl(String liftStyleUrl) {
		this.liftStyleUrl = liftStyleUrl;
	}

	public String getLifeStyleGoogleMap() {
		return this.lifeStyleGoogleMap;
	}

	public void setLifeStyleGoogleMap(String lifeStyleGoogleMap) {
		this.lifeStyleGoogleMap = lifeStyleGoogleMap;
	}

	public Integer getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(Integer languageId) {
		this.languageId = languageId;
	}

	public String getRecommende() {
		return this.recommende;
	}

	public void setRecommende(String recommende) {
		this.recommende = recommende;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContractNo() {
		return this.contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VCommunityWhatNearBy))
			return false;
		VCommunityWhatNearBy castOther = (VCommunityWhatNearBy) other;

		return (this.getCommunityLifestyleId() == castOther
				.getCommunityLifestyleId())
				&& (this.getCommunityId() == castOther.getCommunityId())
				&& ((this.getLifestyleName() == castOther.getLifestyleName()) || (this
						.getLifestyleName() != null
						&& castOther.getLifestyleName() != null && this
						.getLifestyleName()
						.equals(castOther.getLifestyleName())))
				&& ((this.getLifestyleTypeName() == castOther
						.getLifestyleTypeName()) || (this
						.getLifestyleTypeName() != null
						&& castOther.getLifestyleTypeName() != null && this
						.getLifestyleTypeName().equals(
								castOther.getLifestyleTypeName())))
				&& ((this.getLifestyleFullName() == castOther
						.getLifestyleFullName()) || (this
						.getLifestyleFullName() != null
						&& castOther.getLifestyleFullName() != null && this
						.getLifestyleFullName().equals(
								castOther.getLifestyleFullName())))
				&& ((this.getLifestyleDetail() == castOther
						.getLifestyleDetail()) || (this.getLifestyleDetail() != null
						&& castOther.getLifestyleDetail() != null && this
						.getLifestyleDetail().equals(
								castOther.getLifestyleDetail())))
				&& ((this.getDistanceFromHoa() == castOther
						.getDistanceFromHoa()) || (this.getDistanceFromHoa() != null
						&& castOther.getDistanceFromHoa() != null && this
						.getDistanceFromHoa().equals(
								castOther.getDistanceFromHoa())))
				&& ((this.getLifestyleLink() == castOther.getLifestyleLink()) || (this
						.getLifestyleLink() != null
						&& castOther.getLifestyleLink() != null && this
						.getLifestyleLink()
						.equals(castOther.getLifestyleLink())))
				&& ((this.getLifestyleUrl() == castOther.getLifestyleUrl()) || (this
						.getLifestyleUrl() != null
						&& castOther.getLifestyleUrl() != null && this
						.getLifestyleUrl().equals(castOther.getLifestyleUrl())))
				&& ((this.getLifestyleGoogleMap() == castOther
						.getLifestyleGoogleMap()) || (this
						.getLifestyleGoogleMap() != null
						&& castOther.getLifestyleGoogleMap() != null && this
						.getLifestyleGoogleMap().equals(
								castOther.getLifestyleGoogleMap())))
				&& ((this.getGoogleMapLatitude() == castOther
						.getGoogleMapLatitude()) || (this
						.getGoogleMapLatitude() != null
						&& castOther.getGoogleMapLatitude() != null && this
						.getGoogleMapLatitude().equals(
								castOther.getGoogleMapLatitude())))
				&& ((this.getGoogleMapLongtitude() == castOther
						.getGoogleMapLongtitude()) || (this
						.getGoogleMapLongtitude() != null
						&& castOther.getGoogleMapLongtitude() != null && this
						.getGoogleMapLongtitude().equals(
								castOther.getGoogleMapLongtitude())))
				&& ((this.getGoogleMapUrl() == castOther.getGoogleMapUrl()) || (this
						.getGoogleMapUrl() != null
						&& castOther.getGoogleMapUrl() != null && this
						.getGoogleMapUrl().equals(castOther.getGoogleMapUrl())))
				&& ((this.getLiftStyleUrl() == castOther.getLiftStyleUrl()) || (this
						.getLiftStyleUrl() != null
						&& castOther.getLiftStyleUrl() != null && this
						.getLiftStyleUrl().equals(castOther.getLiftStyleUrl())))
				&& ((this.getLifeStyleGoogleMap() == castOther
						.getLifeStyleGoogleMap()) || (this
						.getLifeStyleGoogleMap() != null
						&& castOther.getLifeStyleGoogleMap() != null && this
						.getLifeStyleGoogleMap().equals(
								castOther.getLifeStyleGoogleMap())))
				&& ((this.getLanguageId() == castOther.getLanguageId()) || (this
						.getLanguageId() != null
						&& castOther.getLanguageId() != null && this
						.getLanguageId().equals(castOther.getLanguageId())))
				&& ((this.getRecommende() == castOther.getRecommende()) || (this
						.getRecommende() != null
						&& castOther.getRecommende() != null && this
						.getRecommende().equals(castOther.getRecommende())))
				&& ((this.getAddress() == castOther.getAddress()) || (this
						.getAddress() != null && castOther.getAddress() != null && this
						.getAddress().equals(castOther.getAddress())))
				&& ((this.getContractNo() == castOther.getContractNo()) || (this
						.getContractNo() != null
						&& castOther.getContractNo() != null && this
						.getContractNo().equals(castOther.getContractNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCommunityLifestyleId();
		result = 37 * result + this.getCommunityId();
		result = 37
				* result
				+ (getLifestyleName() == null ? 0 : this.getLifestyleName()
						.hashCode());
		result = 37
				* result
				+ (getLifestyleTypeName() == null ? 0 : this
						.getLifestyleTypeName().hashCode());
		result = 37
				* result
				+ (getLifestyleFullName() == null ? 0 : this
						.getLifestyleFullName().hashCode());
		result = 37
				* result
				+ (getLifestyleDetail() == null ? 0 : this.getLifestyleDetail()
						.hashCode());
		result = 37
				* result
				+ (getDistanceFromHoa() == null ? 0 : this.getDistanceFromHoa()
						.hashCode());
		result = 37
				* result
				+ (getLifestyleLink() == null ? 0 : this.getLifestyleLink()
						.hashCode());
		result = 37
				* result
				+ (getLifestyleUrl() == null ? 0 : this.getLifestyleUrl()
						.hashCode());
		result = 37
				* result
				+ (getLifestyleGoogleMap() == null ? 0 : this
						.getLifestyleGoogleMap().hashCode());
		result = 37
				* result
				+ (getGoogleMapLatitude() == null ? 0 : this
						.getGoogleMapLatitude().hashCode());
		result = 37
				* result
				+ (getGoogleMapLongtitude() == null ? 0 : this
						.getGoogleMapLongtitude().hashCode());
		result = 37
				* result
				+ (getGoogleMapUrl() == null ? 0 : this.getGoogleMapUrl()
						.hashCode());
		result = 37
				* result
				+ (getLiftStyleUrl() == null ? 0 : this.getLiftStyleUrl()
						.hashCode());
		result = 37
				* result
				+ (getLifeStyleGoogleMap() == null ? 0 : this
						.getLifeStyleGoogleMap().hashCode());
		result = 37
				* result
				+ (getLanguageId() == null ? 0 : this.getLanguageId()
						.hashCode());
		result = 37
				* result
				+ (getRecommende() == null ? 0 : this.getRecommende()
						.hashCode());
		result = 37 * result
				+ (getAddress() == null ? 0 : this.getAddress().hashCode());
		result = 37
				* result
				+ (getContractNo() == null ? 0 : this.getContractNo()
						.hashCode());
		return result;
	}

}
