package com.haak.haaksq.form;

// Generated May 29, 2012 11:02:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * VCommunityWhatNearByPictureId generated by hbm2java
 */
public class VCommunityWhatNearByPictureId implements java.io.Serializable {

	private String fileName;
	private String pathName;
	private String fileDetail;
	private String attachUrl;
	private int attachSeq;
	private int attachId;
	private int communityId;

	public VCommunityWhatNearByPictureId() {
	}

	public VCommunityWhatNearByPictureId(String fileName, String pathName,
			String fileDetail, String attachUrl, int attachSeq, int attachId,
			int communityId) {
		this.fileName = fileName;
		this.pathName = pathName;
		this.fileDetail = fileDetail;
		this.attachUrl = attachUrl;
		this.attachSeq = attachSeq;
		this.attachId = attachId;
		this.communityId = communityId;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getPathName() {
		return this.pathName;
	}

	public void setPathName(String pathName) {
		this.pathName = pathName;
	}

	public String getFileDetail() {
		return this.fileDetail;
	}

	public void setFileDetail(String fileDetail) {
		this.fileDetail = fileDetail;
	}

	public String getAttachUrl() {
		return this.attachUrl;
	}

	public void setAttachUrl(String attachUrl) {
		this.attachUrl = attachUrl;
	}

	public int getAttachSeq() {
		return this.attachSeq;
	}

	public void setAttachSeq(int attachSeq) {
		this.attachSeq = attachSeq;
	}

	public int getAttachId() {
		return this.attachId;
	}

	public void setAttachId(int attachId) {
		this.attachId = attachId;
	}

	public int getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(int communityId) {
		this.communityId = communityId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VCommunityWhatNearByPictureId))
			return false;
		VCommunityWhatNearByPictureId castOther = (VCommunityWhatNearByPictureId) other;

		return ((this.getFileName() == castOther.getFileName()) || (this
				.getFileName() != null && castOther.getFileName() != null && this
				.getFileName().equals(castOther.getFileName())))
				&& ((this.getPathName() == castOther.getPathName()) || (this
						.getPathName() != null
						&& castOther.getPathName() != null && this
						.getPathName().equals(castOther.getPathName())))
				&& ((this.getFileDetail() == castOther.getFileDetail()) || (this
						.getFileDetail() != null
						&& castOther.getFileDetail() != null && this
						.getFileDetail().equals(castOther.getFileDetail())))
				&& ((this.getAttachUrl() == castOther.getAttachUrl()) || (this
						.getAttachUrl() != null
						&& castOther.getAttachUrl() != null && this
						.getAttachUrl().equals(castOther.getAttachUrl())))
				&& (this.getAttachSeq() == castOther.getAttachSeq())
				&& (this.getAttachId() == castOther.getAttachId())
				&& (this.getCommunityId() == castOther.getCommunityId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFileName() == null ? 0 : this.getFileName().hashCode());
		result = 37 * result
				+ (getPathName() == null ? 0 : this.getPathName().hashCode());
		result = 37
				* result
				+ (getFileDetail() == null ? 0 : this.getFileDetail()
						.hashCode());
		result = 37 * result
				+ (getAttachUrl() == null ? 0 : this.getAttachUrl().hashCode());
		result = 37 * result + this.getAttachSeq();
		result = 37 * result + this.getAttachId();
		result = 37 * result + this.getCommunityId();
		return result;
	}

}
