package com.haak.haaksq.form;

// Generated Jun 19, 2012 11:53:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * VCommnunityOpportunities generated by hbm2java
 */
public class VCommnunityOpportunities implements java.io.Serializable {

	private VCommnunityOpportunitiesId id;

	public VCommnunityOpportunities() {
	}

	public VCommnunityOpportunities(VCommnunityOpportunitiesId id) {
		this.id = id;
	}

	public VCommnunityOpportunitiesId getId() {
		return this.id;
	}

	public void setId(VCommnunityOpportunitiesId id) {
		this.id = id;
	}

}
