package com.haak.haaksq.form;

// Generated Oct 27, 2012 11:56:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VModuleSubmenu generated by hbm2java
 */
@Entity
@Table(name = "v_module_submenu", catalog = "haaksquare_db")
public class VModuleSubmenu implements java.io.Serializable {

	private VModuleSubmenuId id;
	
	
	

	public VModuleSubmenu() {
	}

	public VModuleSubmenu(VModuleSubmenuId id) {
		this.id = id;
	}

	
	private String menuName;
	private Integer seq;
	private Integer levelMenu;
	private Integer seqSub;
	private Integer parrentSubMenu;
	private int roleModuleActionId;
	private Integer packageId;
	private Integer communityId;
	private Integer roleId;
	private Integer moduleId;
	private String fgView;
	private String fgAdd;
	private String fgEdit;
	private String fgDelete;
	private Integer modifyBy;
	private Date modyfyDate;
	private Integer createBy;
	private Date createDate;

	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "menuId", column = @Column(name = "menu_id", nullable = false)),
})
	public VModuleSubmenuId getId() {
		return this.id;
	}

	public void setId(VModuleSubmenuId id) {
		this.id = id;
	}


	@Column(name = "menu_name", length = 100)
	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	@Column(name = "seq")
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Column(name = "level_menu")
	public Integer getLevelMenu() {
		return this.levelMenu;
	}

	public void setLevelMenu(Integer levelMenu) {
		this.levelMenu = levelMenu;
	}

	@Column(name = "seq_sub")
	public Integer getSeqSub() {
		return this.seqSub;
	}

	public void setSeqSub(Integer seqSub) {
		this.seqSub = seqSub;
	}

	@Column(name = "parrent_sub_menu")
	public Integer getParrentSubMenu() {
		return this.parrentSubMenu;
	}

	public void setParrentSubMenu(Integer parrentSubMenu) {
		this.parrentSubMenu = parrentSubMenu;
	}

	@Column(name = "role_module_action_id", nullable = false)
	public int getRoleModuleActionId() {
		return this.roleModuleActionId;
	}

	public void setRoleModuleActionId(int roleModuleActionId) {
		this.roleModuleActionId = roleModuleActionId;
	}

	@Column(name = "package_id")
	public Integer getPackageId() {
		return this.packageId;
	}

	public void setPackageId(Integer packageId) {
		this.packageId = packageId;
	}

	@Column(name = "community_id")
	public Integer getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(Integer communityId) {
		this.communityId = communityId;
	}

	@Column(name = "role_id")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "module_id")
	public Integer getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name = "fg_view", length = 1)
	public String getFgView() {
		return this.fgView;
	}

	public void setFgView(String fgView) {
		this.fgView = fgView;
	}

	@Column(name = "fg_Add", length = 1)
	public String getFgAdd() {
		return this.fgAdd;
	}

	public void setFgAdd(String fgAdd) {
		this.fgAdd = fgAdd;
	}

	@Column(name = "fg_edit", length = 1)
	public String getFgEdit() {
		return this.fgEdit;
	}

	public void setFgEdit(String fgEdit) {
		this.fgEdit = fgEdit;
	}

	@Column(name = "fg_delete", length = 1)
	public String getFgDelete() {
		return this.fgDelete;
	}

	public void setFgDelete(String fgDelete) {
		this.fgDelete = fgDelete;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Column(name = "modyfy_date", length = 19)
	public Date getModyfyDate() {
		return this.modyfyDate;
	}

	public void setModyfyDate(Date modyfyDate) {
		this.modyfyDate = modyfyDate;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	
}
