package com.haak.haaksq.form;

// Generated Aug 15, 2012 2:56:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Worklist2 generated by hbm2java
 */
public class Worklist2 implements java.io.Serializable {

	private Integer worklistId;
	private Integer worklistSeq;
	private Integer communityId;
	private Integer worklistTypeId;
	private Integer worklistSubjectId;
	private String worklistName;
	private String worklistDetail;
	private String phone;
	private Integer fromUserId;
	public Integer getFromUserId() {
		return fromUserId;
	}

	public void setFromUserId(Integer fromUserId) {
		this.fromUserId = fromUserId;
	}

	private String fromUserName;
	private String fromName;
	private String fromEmail;
	private String toUserName;
	private Integer roleId;
	private Integer worklistStatusId;
	private String jobDetails;
	private Integer modifyBy;
	private Date modifyDate;
	private Integer createBy;
	private Date createDate;
	private Integer addressId;

	public Integer getAddressId() {
		return addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	public Worklist2() {
	}

	public Worklist2(Integer worklistSeq, Integer communityId,
			Integer worklistTypeId, Integer worklistSubjectId,
			String worklistName, String worklistDetail, String phone,
			String fromUserName, String fromName, String fromEmail,
			String toUserName, Integer roleId, Integer worklistStatusId,
			String jobDetails, Integer modifyBy, Date modifyDate,
			Integer createBy, Date createDate) {
		this.worklistSeq = worklistSeq;
		this.communityId = communityId;
		this.worklistTypeId = worklistTypeId;
		this.worklistSubjectId = worklistSubjectId;
		this.worklistName = worklistName;
		this.worklistDetail = worklistDetail;
		this.phone = phone;
		this.fromUserName = fromUserName;
		this.fromName = fromName;
		this.fromEmail = fromEmail;
		this.toUserName = toUserName;
		this.roleId = roleId;
		this.worklistStatusId = worklistStatusId;
		this.jobDetails = jobDetails;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.createDate = createDate;
	}

	public Integer getWorklistId() {
		return this.worklistId;
	}

	public void setWorklistId(Integer worklistId) {
		this.worklistId = worklistId;
	}

	public Integer getWorklistSeq() {
		return this.worklistSeq;
	}

	public void setWorklistSeq(Integer worklistSeq) {
		this.worklistSeq = worklistSeq;
	}

	public Integer getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(Integer communityId) {
		this.communityId = communityId;
	}

	public Integer getWorklistTypeId() {
		return this.worklistTypeId;
	}

	public void setWorklistTypeId(Integer worklistTypeId) {
		this.worklistTypeId = worklistTypeId;
	}

	public Integer getWorklistSubjectId() {
		return this.worklistSubjectId;
	}

	public void setWorklistSubjectId(Integer worklistSubjectId) {
		this.worklistSubjectId = worklistSubjectId;
	}

	public String getWorklistName() {
		return this.worklistName;
	}

	public void setWorklistName(String worklistName) {
		this.worklistName = worklistName;
	}

	public String getWorklistDetail() {
		return this.worklistDetail;
	}

	public void setWorklistDetail(String worklistDetail) {
		this.worklistDetail = worklistDetail;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFromUserName() {
		return this.fromUserName;
	}

	public void setFromUserName(String fromUserName) {
		this.fromUserName = fromUserName;
	}

	public String getFromName() {
		return this.fromName;
	}

	public void setFromName(String fromName) {
		this.fromName = fromName;
	}

	public String getFromEmail() {
		return this.fromEmail;
	}

	public void setFromEmail(String fromEmail) {
		this.fromEmail = fromEmail;
	}

	public String getToUserName() {
		return this.toUserName;
	}

	public void setToUserName(String toUserName) {
		this.toUserName = toUserName;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public Integer getWorklistStatusId() {
		return this.worklistStatusId;
	}

	public void setWorklistStatusId(Integer worklistStatusId) {
		this.worklistStatusId = worklistStatusId;
	}

	public String getJobDetails() {
		return this.jobDetails;
	}

	public void setJobDetails(String jobDetails) {
		this.jobDetails = jobDetails;
	}

	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
