package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BlogNews generated by hbm2java
 */
@Entity
@Table(name = "blog_news", catalog = "haaksquare_db")
public class BlogNews implements java.io.Serializable {

	private int newsId;
	private String commuId;
	private String type;
	private String header;
	private String details;
	private String createById;
	private Date createDate;

	public BlogNews() {
	}

	public BlogNews(int newsId, String type, String header, String details) {
		this.newsId = newsId;
		this.type = type;
		this.header = header;
		this.details = details;
	}

	public BlogNews(int newsId, String commuId, String type, String header,
			String details, String createById, Date createDate) {
		this.newsId = newsId;
		this.commuId = commuId;
		this.type = type;
		this.header = header;
		this.details = details;
		this.createById = createById;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "news_id", unique = true, nullable = false)
	public int getNewsId() {
		return this.newsId;
	}

	public void setNewsId(int newsId) {
		this.newsId = newsId;
	}

	@Column(name = "commu_id", length = 5)
	public String getCommuId() {
		return this.commuId;
	}

	public void setCommuId(String commuId) {
		this.commuId = commuId;
	}

	@Column(name = "type", nullable = false, length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "header", nullable = false, length = 1000)
	public String getHeader() {
		return this.header;
	}

	public void setHeader(String header) {
		this.header = header;
	}

	@Column(name = "details", nullable = false, length = 4000)
	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	@Column(name = "create_by_id", length = 50)
	public String getCreateById() {
		return this.createById;
	}

	public void setCreateById(String createById) {
		this.createById = createById;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
