package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommunityGroupId generated by hbm2java
 */
@Embeddable
public class CommunityGroupId implements java.io.Serializable {

	private int communityId;
	private int communityGroupId;

	public CommunityGroupId() {
	}

	public CommunityGroupId(int communityId, int communityGroupId) {
		this.communityId = communityId;
		this.communityGroupId = communityGroupId;
	}

	@Column(name = "community_id", nullable = false)
	public int getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(int communityId) {
		this.communityId = communityId;
	}

	@Column(name = "community_group_id", nullable = false)
	public int getCommunityGroupId() {
		return this.communityGroupId;
	}

	public void setCommunityGroupId(int communityGroupId) {
		this.communityGroupId = communityGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommunityGroupId))
			return false;
		CommunityGroupId castOther = (CommunityGroupId) other;

		return (this.getCommunityId() == castOther.getCommunityId())
				&& (this.getCommunityGroupId() == castOther
						.getCommunityGroupId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCommunityId();
		result = 37 * result + this.getCommunityGroupId();
		return result;
	}

}
