package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CommunitySaleRent generated by hbm2java
 */
@Entity
@Table(name = "community_sale_rent", catalog = "haaksquare_db")
public class CommunitySaleRent implements java.io.Serializable {

	private CommunitySaleRentId id;
	private Integer saleRentTypeId;
	private Integer communityTypeId;
	private String contractPerson;
	private String contractNumber;
	private String address;
	private Long valueAmount;
	private BigDecimal landSpace;
	private BigDecimal liveSpace;
	private Integer bedRoom;
	private Integer bathRoom;
	private String salesRentDetail;
	private String exteriorOption;
	private String interiorOption;
	private String contract;
	private String salesRentUrl;
	private Date modifyDate;
	private Integer createBy;
	private Date createDate;

	public CommunitySaleRent() {
	}

	public CommunitySaleRent(CommunitySaleRentId id) {
		this.id = id;
	}

	public CommunitySaleRent(CommunitySaleRentId id, Integer saleRentTypeId,
			Integer communityTypeId, String contractPerson,
			String contractNumber, String address, Long valueAmount,
			BigDecimal landSpace, BigDecimal liveSpace, Integer bedRoom,
			Integer bathRoom, String salesRentDetail, String exteriorOption,
			String interiorOption, String contract, String salesRentUrl,
			Date modifyDate, Integer createBy, Date createDate) {
		this.id = id;
		this.saleRentTypeId = saleRentTypeId;
		this.communityTypeId = communityTypeId;
		this.contractPerson = contractPerson;
		this.contractNumber = contractNumber;
		this.address = address;
		this.valueAmount = valueAmount;
		this.landSpace = landSpace;
		this.liveSpace = liveSpace;
		this.bedRoom = bedRoom;
		this.bathRoom = bathRoom;
		this.salesRentDetail = salesRentDetail;
		this.exteriorOption = exteriorOption;
		this.interiorOption = interiorOption;
		this.contract = contract;
		this.salesRentUrl = salesRentUrl;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.createDate = createDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "communitySaleRentId", column = @Column(name = "community_sale_rent_id", nullable = false)),
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)) })
	public CommunitySaleRentId getId() {
		return this.id;
	}

	public void setId(CommunitySaleRentId id) {
		this.id = id;
	}

	@Column(name = "sale_rent_type_id")
	public Integer getSaleRentTypeId() {
		return this.saleRentTypeId;
	}

	public void setSaleRentTypeId(Integer saleRentTypeId) {
		this.saleRentTypeId = saleRentTypeId;
	}

	@Column(name = "community_type_id")
	public Integer getCommunityTypeId() {
		return this.communityTypeId;
	}

	public void setCommunityTypeId(Integer communityTypeId) {
		this.communityTypeId = communityTypeId;
	}

	@Column(name = "contract_person", length = 300)
	public String getContractPerson() {
		return this.contractPerson;
	}

	public void setContractPerson(String contractPerson) {
		this.contractPerson = contractPerson;
	}

	@Column(name = "contract_number", length = 300)
	public String getContractNumber() {
		return this.contractNumber;
	}

	public void setContractNumber(String contractNumber) {
		this.contractNumber = contractNumber;
	}

	@Column(name = "address", length = 1000)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "value_amount", precision = 10, scale = 0)
	public Long getValueAmount() {
		return this.valueAmount;
	}

	public void setValueAmount(Long valueAmount) {
		this.valueAmount = valueAmount;
	}

	@Column(name = "land_space", precision = 10)
	public BigDecimal getLandSpace() {
		return this.landSpace;
	}

	public void setLandSpace(BigDecimal landSpace) {
		this.landSpace = landSpace;
	}

	@Column(name = "live_space", precision = 10)
	public BigDecimal getLiveSpace() {
		return this.liveSpace;
	}

	public void setLiveSpace(BigDecimal liveSpace) {
		this.liveSpace = liveSpace;
	}

	@Column(name = "bed_room")
	public Integer getBedRoom() {
		return this.bedRoom;
	}

	public void setBedRoom(Integer bedRoom) {
		this.bedRoom = bedRoom;
	}

	@Column(name = "bath_room")
	public Integer getBathRoom() {
		return this.bathRoom;
	}

	public void setBathRoom(Integer bathRoom) {
		this.bathRoom = bathRoom;
	}

	@Column(name = "sales_rent_detail", length = 1000)
	public String getSalesRentDetail() {
		return this.salesRentDetail;
	}

	public void setSalesRentDetail(String salesRentDetail) {
		this.salesRentDetail = salesRentDetail;
	}

	@Column(name = "exterior_option", length = 1000)
	public String getExteriorOption() {
		return this.exteriorOption;
	}

	public void setExteriorOption(String exteriorOption) {
		this.exteriorOption = exteriorOption;
	}

	@Column(name = "interior_option", length = 1000)
	public String getInteriorOption() {
		return this.interiorOption;
	}

	public void setInteriorOption(String interiorOption) {
		this.interiorOption = interiorOption;
	}

	@Column(name = "contract", length = 1000)
	public String getContract() {
		return this.contract;
	}

	public void setContract(String contract) {
		this.contract = contract;
	}

	@Column(name = "sales_rent_url", length = 1000)
	public String getSalesRentUrl() {
		return this.salesRentUrl;
	}

	public void setSalesRentUrl(String salesRentUrl) {
		this.salesRentUrl = salesRentUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
