package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommunityResourceId generated by hbm2java
 */
@Embeddable
public class CommunityResourceId implements java.io.Serializable {

	private int communityResourceId;
	private int communityId;
	private int seq;

	public CommunityResourceId() {
	}

	public CommunityResourceId(int communityResourceId, int communityId, int seq) {
		this.communityResourceId = communityResourceId;
		this.communityId = communityId;
		this.seq = seq;
	}

	@Column(name = "community_resource_id", nullable = false)
	public int getCommunityResourceId() {
		return this.communityResourceId;
	}

	public void setCommunityResourceId(int communityResourceId) {
		this.communityResourceId = communityResourceId;
	}

	@Column(name = "community_id", nullable = false)
	public int getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(int communityId) {
		this.communityId = communityId;
	}

	@Column(name = "seq", nullable = false)
	public int getSeq() {
		return this.seq;
	}

	public void setSeq(int seq) {
		this.seq = seq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommunityResourceId))
			return false;
		CommunityResourceId castOther = (CommunityResourceId) other;

		return (this.getCommunityResourceId() == castOther
				.getCommunityResourceId())
				&& (this.getCommunityId() == castOther.getCommunityId())
				&& (this.getSeq() == castOther.getSeq());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCommunityResourceId();
		result = 37 * result + this.getCommunityId();
		result = 37 * result + this.getSeq();
		return result;
	}

}
