package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CommunityResource generated by hbm2java
 */
@Entity
@Table(name = "community_resource", catalog = "haaksquare_db")
public class CommunityResource implements java.io.Serializable {

	private CommunityResourceId id;
	private String fgOpen;
	private String fgPublic;
	private Integer resourceCategoryId;
	private Integer resourceSubCategoryId;
	private String resourceName;
	private String resourceDetail;
	private String year;
	private Integer unit;
	private String fgShow;
	private Date modifyDate;
	private Integer createBy;
	private Date createDate;
	private Integer modifyBy;

	public CommunityResource() {
	}

	public CommunityResource(CommunityResourceId id) {
		this.id = id;
	}

	public CommunityResource(CommunityResourceId id, String fgOpen,
			String fgPublic, Integer resourceCategoryId,
			Integer resourceSubCategoryId, String resourceName,
			String resourceDetail, String year, Integer unit, String fgShow,
			Date modifyDate, Integer createBy, Date createDate, Integer modifyBy) {
		this.id = id;
		this.fgOpen = fgOpen;
		this.fgPublic = fgPublic;
		this.resourceCategoryId = resourceCategoryId;
		this.resourceSubCategoryId = resourceSubCategoryId;
		this.resourceName = resourceName;
		this.resourceDetail = resourceDetail;
		this.year = year;
		this.unit = unit;
		this.fgShow = fgShow;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.createDate = createDate;
		this.modifyBy = modifyBy;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "communityResourceId", column = @Column(name = "community_resource_id", nullable = false)),
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)),
			@AttributeOverride(name = "seq", column = @Column(name = "seq", nullable = false)) })
	public CommunityResourceId getId() {
		return this.id;
	}

	public void setId(CommunityResourceId id) {
		this.id = id;
	}

	@Column(name = "fg_open", length = 1)
	public String getFgOpen() {
		return this.fgOpen;
	}

	public void setFgOpen(String fgOpen) {
		this.fgOpen = fgOpen;
	}

	@Column(name = "fg_public", length = 1)
	public String getFgPublic() {
		return this.fgPublic;
	}

	public void setFgPublic(String fgPublic) {
		this.fgPublic = fgPublic;
	}

	@Column(name = "resource_category_id")
	public Integer getResourceCategoryId() {
		return this.resourceCategoryId;
	}

	public void setResourceCategoryId(Integer resourceCategoryId) {
		this.resourceCategoryId = resourceCategoryId;
	}

	@Column(name = "resource_sub_category_id")
	public Integer getResourceSubCategoryId() {
		return this.resourceSubCategoryId;
	}

	public void setResourceSubCategoryId(Integer resourceSubCategoryId) {
		this.resourceSubCategoryId = resourceSubCategoryId;
	}

	@Column(name = "resource_name", length = 500)
	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	@Column(name = "resource_detail", length = 2000)
	public String getResourceDetail() {
		return this.resourceDetail;
	}

	public void setResourceDetail(String resourceDetail) {
		this.resourceDetail = resourceDetail;
	}

	@Column(name = "year", length = 4)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "unit")
	public Integer getUnit() {
		return this.unit;
	}

	public void setUnit(Integer unit) {
		this.unit = unit;
	}

	@Column(name = "fg_show", length = 1)
	public String getFgShow() {
		return this.fgShow;
	}

	public void setFgShow(String fgShow) {
		this.fgShow = fgShow;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

}
