package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CommunityNew generated by hbm2java
 */
@Entity
@Table(name = "community_new", catalog = "haaksquare_db")
public class CommunityNew implements java.io.Serializable {

	private Integer communityNewId;
	private int communityId;
	private int newSeq;
	private String fgPublic;
	private String newSubject;
	private String newDetail;
	private String lifestyleLink;
	private String lifestyleUrl;
	private String lifestyleGoogleMap;
	private String googleMapLatitude;
	private String googleMapLongtitude;
	private String googleMapUrl;
	private Date modifyDate;
	private Integer createBy;
	private Date createDate;
	private Integer modifyBy;
	private String fromSource;
	private String fgOpen;

	public CommunityNew() {
	}

	public CommunityNew(int communityId, int newSeq) {
		this.communityId = communityId;
		this.newSeq = newSeq;
	}

	public CommunityNew(int communityId, int newSeq, String fgPublic,
			String newSubject, String newDetail, String lifestyleLink,
			String lifestyleUrl, String lifestyleGoogleMap,
			String googleMapLatitude, String googleMapLongtitude,
			String googleMapUrl, Date modifyDate, Integer createBy,
			Date createDate, Integer modifyBy, String fromSource, String fgOpen) {
		this.communityId = communityId;
		this.newSeq = newSeq;
		this.fgPublic = fgPublic;
		this.newSubject = newSubject;
		this.newDetail = newDetail;
		this.lifestyleLink = lifestyleLink;
		this.lifestyleUrl = lifestyleUrl;
		this.lifestyleGoogleMap = lifestyleGoogleMap;
		this.googleMapLatitude = googleMapLatitude;
		this.googleMapLongtitude = googleMapLongtitude;
		this.googleMapUrl = googleMapUrl;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.createDate = createDate;
		this.modifyBy = modifyBy;
		this.fromSource = fromSource;
		this.fgOpen = fgOpen;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "community_new_id", unique = true, nullable = false)
	public Integer getCommunityNewId() {
		return this.communityNewId;
	}

	public void setCommunityNewId(Integer communityNewId) {
		this.communityNewId = communityNewId;
	}

	@Column(name = "community_id", nullable = false)
	public int getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(int communityId) {
		this.communityId = communityId;
	}

	@Column(name = "new_seq", nullable = false)
	public int getNewSeq() {
		return this.newSeq;
	}

	public void setNewSeq(int newSeq) {
		this.newSeq = newSeq;
	}

	@Column(name = "fg_public", length = 1)
	public String getFgPublic() {
		return this.fgPublic;
	}

	public void setFgPublic(String fgPublic) {
		this.fgPublic = fgPublic;
	}

	@Column(name = "new_subject", length = 1000)
	public String getNewSubject() {
		return this.newSubject;
	}

	public void setNewSubject(String newSubject) {
		this.newSubject = newSubject;
	}

	@Column(name = "new_detail", length = 2000)
	public String getNewDetail() {
		return this.newDetail;
	}

	public void setNewDetail(String newDetail) {
		this.newDetail = newDetail;
	}

	@Column(name = "lifestyle_link", length = 300)
	public String getLifestyleLink() {
		return this.lifestyleLink;
	}

	public void setLifestyleLink(String lifestyleLink) {
		this.lifestyleLink = lifestyleLink;
	}

	@Column(name = "lifestyle_url", length = 1000)
	public String getLifestyleUrl() {
		return this.lifestyleUrl;
	}

	public void setLifestyleUrl(String lifestyleUrl) {
		this.lifestyleUrl = lifestyleUrl;
	}

	@Column(name = "lifestyle_google_map", length = 1000)
	public String getLifestyleGoogleMap() {
		return this.lifestyleGoogleMap;
	}

	public void setLifestyleGoogleMap(String lifestyleGoogleMap) {
		this.lifestyleGoogleMap = lifestyleGoogleMap;
	}

	@Column(name = "google_map_latitude", length = 500)
	public String getGoogleMapLatitude() {
		return this.googleMapLatitude;
	}

	public void setGoogleMapLatitude(String googleMapLatitude) {
		this.googleMapLatitude = googleMapLatitude;
	}

	@Column(name = "google_map_longtitude", length = 500)
	public String getGoogleMapLongtitude() {
		return this.googleMapLongtitude;
	}

	public void setGoogleMapLongtitude(String googleMapLongtitude) {
		this.googleMapLongtitude = googleMapLongtitude;
	}

	@Column(name = "google_map_url", length = 500)
	public String getGoogleMapUrl() {
		return this.googleMapUrl;
	}

	public void setGoogleMapUrl(String googleMapUrl) {
		this.googleMapUrl = googleMapUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Column(name = "from_source", length = 1000)
	public String getFromSource() {
		return this.fromSource;
	}

	public void setFromSource(String fromSource) {
		this.fromSource = fromSource;
	}

	@Column(name = "fg_open", length = 1)
	public String getFgOpen() {
		return this.fgOpen;
	}

	public void setFgOpen(String fgOpen) {
		this.fgOpen = fgOpen;
	}

}
