package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModuleActivity generated by hbm2java
 */
@Entity
@Table(name = "module_activity", catalog = "haaksquare_db")
public class ModuleActivity implements java.io.Serializable {

	private ModuleActivityId id;

	public ModuleActivity() {
	}

	public ModuleActivity(ModuleActivityId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "moduleActivityId", column = @Column(name = "module_activity_id", nullable = false)),
			@AttributeOverride(name = "roleModuleId", column = @Column(name = "role_module_id", nullable = false)),
			@AttributeOverride(name = "moduleId", column = @Column(name = "module_id", nullable = false)),
			@AttributeOverride(name = "activityId", column = @Column(name = "activity_id", nullable = false)) })
	public ModuleActivityId getId() {
		return this.id;
	}

	public void setId(ModuleActivityId id) {
		this.id = id;
	}

}
