package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstAmenitiesId generated by hbm2java
 */
@Embeddable
public class MstAmenitiesId implements java.io.Serializable {

	private int amenitiesId;
	private int langaugeId;

	public MstAmenitiesId() {
	}

	public MstAmenitiesId(int amenitiesId, int langaugeId) {
		this.amenitiesId = amenitiesId;
		this.langaugeId = langaugeId;
	}

	@Column(name = "amenities_id", nullable = false)
	public int getAmenitiesId() {
		return this.amenitiesId;
	}

	public void setAmenitiesId(int amenitiesId) {
		this.amenitiesId = amenitiesId;
	}

	@Column(name = "langauge_id", nullable = false)
	public int getLangaugeId() {
		return this.langaugeId;
	}

	public void setLangaugeId(int langaugeId) {
		this.langaugeId = langaugeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MstAmenitiesId))
			return false;
		MstAmenitiesId castOther = (MstAmenitiesId) other;

		return (this.getAmenitiesId() == castOther.getAmenitiesId())
				&& (this.getLangaugeId() == castOther.getLangaugeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAmenitiesId();
		result = 37 * result + this.getLangaugeId();
		return result;
	}

}
