package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstContractNumberCategory generated by hbm2java
 */
@Entity
@Table(name = "mst_contract_number_category", catalog = "haaksquare_db")
public class MstContractNumberCategory implements java.io.Serializable {

	private MstContractNumberCategoryId id;
	private String contractNumberCategoryName;
	private Integer modifyBy;
	private Date modifyDate;
	private Integer createBy;
	private Date createDate;

	public MstContractNumberCategory() {
	}

	public MstContractNumberCategory(MstContractNumberCategoryId id) {
		this.id = id;
	}

	public MstContractNumberCategory(MstContractNumberCategoryId id,
			String contractNumberCategoryName, Integer modifyBy,
			Date modifyDate, Integer createBy, Date createDate) {
		this.id = id;
		this.contractNumberCategoryName = contractNumberCategoryName;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.createDate = createDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "contractNumberCategoryId", column = @Column(name = "contract_number_category_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public MstContractNumberCategoryId getId() {
		return this.id;
	}

	public void setId(MstContractNumberCategoryId id) {
		this.id = id;
	}

	@Column(name = "contract_number_category_name", length = 100)
	public String getContractNumberCategoryName() {
		return this.contractNumberCategoryName;
	}

	public void setContractNumberCategoryName(String contractNumberCategoryName) {
		this.contractNumberCategoryName = contractNumberCategoryName;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
