package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MstCommunity generated by hbm2java
 */
@Entity
@Table(name = "mst_community", catalog = "haaksquare_db")
public class MstCommunity implements java.io.Serializable {

	private int communityId;
	private Integer communityGroupId;
	private String communityName;
	private String company;
	private Integer addressId;

	public MstCommunity() {
	}

	public MstCommunity(int communityId, String communityName) {
		this.communityId = communityId;
		this.communityName = communityName;
	}

	public MstCommunity(int communityId, Integer communityGroupId,
			String communityName, String company, Integer addressId) {
		this.communityId = communityId;
		this.communityGroupId = communityGroupId;
		this.communityName = communityName;
		this.company = company;
		this.addressId = addressId;
	}

	@Id
	@Column(name = "community_id", unique = true, nullable = false)
	public int getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(int communityId) {
		this.communityId = communityId;
	}

	@Column(name = "community_group_id")
	public Integer getCommunityGroupId() {
		return this.communityGroupId;
	}

	public void setCommunityGroupId(Integer communityGroupId) {
		this.communityGroupId = communityGroupId;
	}

	@Column(name = "community_name", nullable = false, length = 200)
	public String getCommunityName() {
		return this.communityName;
	}

	public void setCommunityName(String communityName) {
		this.communityName = communityName;
	}

	@Column(name = "company", length = 200)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "address_id")
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

}
