package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstLifestyle generated by hbm2java
 */
@Entity
@Table(name = "mst_lifestyle", catalog = "haaksquare_db")
public class MstLifestyle implements java.io.Serializable {

	private int lifestyleId;
	private Integer languageId;
	private String lifestyleName;
	private Integer modifyBy;
	private Date modifyDate;
	private String liftStyleUrl;
	private String lifeStyleGoogleMap;
	private Integer createBy;
	private Date createDate;

	public MstLifestyle() {
	}

	public MstLifestyle(int lifestyleId) {
		this.lifestyleId = lifestyleId;
	}

	public MstLifestyle(int lifestyleId, Integer languageId,
			String lifestyleName, Integer modifyBy, Date modifyDate,
			String liftStyleUrl, String lifeStyleGoogleMap, Integer createBy,
			Date createDate) {
		this.lifestyleId = lifestyleId;
		this.languageId = languageId;
		this.lifestyleName = lifestyleName;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.liftStyleUrl = liftStyleUrl;
		this.lifeStyleGoogleMap = lifeStyleGoogleMap;
		this.createBy = createBy;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "lifestyle_id", unique = true, nullable = false)
	public int getLifestyleId() {
		return this.lifestyleId;
	}

	public void setLifestyleId(int lifestyleId) {
		this.lifestyleId = lifestyleId;
	}

	@Column(name = "language_id")
	public Integer getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(Integer languageId) {
		this.languageId = languageId;
	}

	@Column(name = "lifestyle_name")
	public String getLifestyleName() {
		return this.lifestyleName;
	}

	public void setLifestyleName(String lifestyleName) {
		this.lifestyleName = lifestyleName;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "lift_style_url", length = 1000)
	public String getLiftStyleUrl() {
		return this.liftStyleUrl;
	}

	public void setLiftStyleUrl(String liftStyleUrl) {
		this.liftStyleUrl = liftStyleUrl;
	}

	@Column(name = "life_style_google_map", length = 1000)
	public String getLifeStyleGoogleMap() {
		return this.lifeStyleGoogleMap;
	}

	public void setLifeStyleGoogleMap(String lifeStyleGoogleMap) {
		this.lifeStyleGoogleMap = lifeStyleGoogleMap;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
