package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstModuleId generated by hbm2java
 */
@Embeddable
public class MstModuleId implements java.io.Serializable {

	private int moduleId;
	private int languageId;

	public MstModuleId() {
	}

	public MstModuleId(int moduleId, int languageId) {
		this.moduleId = moduleId;
		this.languageId = languageId;
	}

	@Column(name = "module_id", nullable = false)
	public int getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(int moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MstModuleId))
			return false;
		MstModuleId castOther = (MstModuleId) other;

		return (this.getModuleId() == castOther.getModuleId())
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getModuleId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
