package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstMenu generated by hbm2java
 */
@Entity
@Table(name = "mst_menu", catalog = "haaksquare_db")
public class MstMenu implements java.io.Serializable {

	private MstMenuId id;
	private String menuName;
	private String menuUrl;
	private String menuImageUrl;
	private Integer modifyBy;
	private Date modifyDate;
	private Integer createBy;
	private Date createDate;
	private Integer seq;
	private Integer levelMenu;
	private Integer seqSub;
	private Integer parrentSubMenu;

	public MstMenu() {
	}

	public MstMenu(MstMenuId id, String menuUrl) {
		this.id = id;
		this.menuUrl = menuUrl;
	}

	public MstMenu(MstMenuId id, String menuName, String menuUrl,
			String menuImageUrl, Integer modifyBy, Date modifyDate,
			Integer createBy, Date createDate, Integer seq, Integer levelMenu,
			Integer seqSub, Integer parrentSubMenu) {
		this.id = id;
		this.menuName = menuName;
		this.menuUrl = menuUrl;
		this.menuImageUrl = menuImageUrl;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.createDate = createDate;
		this.seq = seq;
		this.levelMenu = levelMenu;
		this.seqSub = seqSub;
		this.parrentSubMenu = parrentSubMenu;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "menuId", column = @Column(name = "menu_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public MstMenuId getId() {
		return this.id;
	}

	public void setId(MstMenuId id) {
		this.id = id;
	}

	@Column(name = "menu_name", length = 100)
	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	@Column(name = "menu_url", nullable = false, length = 100)
	public String getMenuUrl() {
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	@Column(name = "menu_image_url", length = 100)
	public String getMenuImageUrl() {
		return this.menuImageUrl;
	}

	public void setMenuImageUrl(String menuImageUrl) {
		this.menuImageUrl = menuImageUrl;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "seq")
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Column(name = "level_menu")
	public Integer getLevelMenu() {
		return this.levelMenu;
	}

	public void setLevelMenu(Integer levelMenu) {
		this.levelMenu = levelMenu;
	}

	@Column(name = "seq_sub")
	public Integer getSeqSub() {
		return this.seqSub;
	}

	public void setSeqSub(Integer seqSub) {
		this.seqSub = seqSub;
	}

	@Column(name = "parrent_sub_menu")
	public Integer getParrentSubMenu() {
		return this.parrentSubMenu;
	}

	public void setParrentSubMenu(Integer parrentSubMenu) {
		this.parrentSubMenu = parrentSubMenu;
	}

}
