package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstMenuId generated by hbm2java
 */
@Embeddable
public class MstMenuId implements java.io.Serializable {

	private int menuId;
	private int languageId;

	public MstMenuId() {
	}

	public MstMenuId(int menuId, int languageId) {
		this.menuId = menuId;
		this.languageId = languageId;
	}

	@Column(name = "menu_id", nullable = false)
	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MstMenuId))
			return false;
		MstMenuId castOther = (MstMenuId) other;

		return (this.getMenuId() == castOther.getMenuId())
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMenuId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
