package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstProvinceId generated by hbm2java
 */
@Embeddable
public class MstProvinceId implements java.io.Serializable {

	private String provinceId;
	private int languageId;

	public MstProvinceId() {
	}

	public MstProvinceId(String provinceId, int languageId) {
		this.provinceId = provinceId;
		this.languageId = languageId;
	}

	@Column(name = "province_id", nullable = false, length = 10)
	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MstProvinceId))
			return false;
		MstProvinceId castOther = (MstProvinceId) other;

		return ((this.getProvinceId() == castOther.getProvinceId()) || (this
				.getProvinceId() != null && castOther.getProvinceId() != null && this
				.getProvinceId().equals(castOther.getProvinceId())))
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getProvinceId() == null ? 0 : this.getProvinceId()
						.hashCode());
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
