package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstTumbolId generated by hbm2java
 */
@Embeddable
public class MstTumbolId implements java.io.Serializable {

	private String tumbolId;
	private int languageId;

	public MstTumbolId() {
	}

	public MstTumbolId(String tumbolId, int languageId) {
		this.tumbolId = tumbolId;
		this.languageId = languageId;
	}

	@Column(name = "tumbol_id", nullable = false, length = 10)
	public String getTumbolId() {
		return this.tumbolId;
	}

	public void setTumbolId(String tumbolId) {
		this.tumbolId = tumbolId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MstTumbolId))
			return false;
		MstTumbolId castOther = (MstTumbolId) other;

		return ((this.getTumbolId() == castOther.getTumbolId()) || (this
				.getTumbolId() != null && castOther.getTumbolId() != null && this
				.getTumbolId().equals(castOther.getTumbolId())))
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTumbolId() == null ? 0 : this.getTumbolId().hashCode());
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
