package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstWorklistSubType generated by hbm2java
 */
@Entity
@Table(name = "mst_worklist_sub_type", catalog = "haaksquare_db")
public class MstWorklistSubType implements java.io.Serializable {

	private int worklistSubTypeId;
	private Integer worklistTypeId;
	private String worklistSubTypeName;
	private Integer modifyBy;
	private Date modifyDate;
	private Integer createBy;
	private Date createDate;

	public MstWorklistSubType() {
	}

	public MstWorklistSubType(int worklistSubTypeId) {
		this.worklistSubTypeId = worklistSubTypeId;
	}

	public MstWorklistSubType(int worklistSubTypeId, Integer worklistTypeId,
			String worklistSubTypeName, Integer modifyBy, Date modifyDate,
			Integer createBy, Date createDate) {
		this.worklistSubTypeId = worklistSubTypeId;
		this.worklistTypeId = worklistTypeId;
		this.worklistSubTypeName = worklistSubTypeName;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "worklist_sub_type_id", unique = true, nullable = false)
	public int getWorklistSubTypeId() {
		return this.worklistSubTypeId;
	}

	public void setWorklistSubTypeId(int worklistSubTypeId) {
		this.worklistSubTypeId = worklistSubTypeId;
	}

	@Column(name = "worklist_type_id")
	public Integer getWorklistTypeId() {
		return this.worklistTypeId;
	}

	public void setWorklistTypeId(Integer worklistTypeId) {
		this.worklistTypeId = worklistTypeId;
	}

	@Column(name = "worklist_sub_type_name", length = 200)
	public String getWorklistSubTypeName() {
		return this.worklistSubTypeName;
	}

	public void setWorklistSubTypeName(String worklistSubTypeName) {
		this.worklistSubTypeName = worklistSubTypeName;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
