package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstWorklistSubjectId generated by hbm2java
 */
@Embeddable
public class MstWorklistSubjectId implements java.io.Serializable {

	private int worklistSubjectId;
	private int roleId;

	public MstWorklistSubjectId() {
	}

	public MstWorklistSubjectId(int worklistSubjectId, int roleId) {
		this.worklistSubjectId = worklistSubjectId;
		this.roleId = roleId;
	}

	@Column(name = "worklist_subject_id", nullable = false)
	public int getWorklistSubjectId() {
		return this.worklistSubjectId;
	}

	public void setWorklistSubjectId(int worklistSubjectId) {
		this.worklistSubjectId = worklistSubjectId;
	}

	@Column(name = "role_id", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MstWorklistSubjectId))
			return false;
		MstWorklistSubjectId castOther = (MstWorklistSubjectId) other;

		return (this.getWorklistSubjectId() == castOther.getWorklistSubjectId())
				&& (this.getRoleId() == castOther.getRoleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWorklistSubjectId();
		result = 37 * result + this.getRoleId();
		return result;
	}

}
