package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MstWorklistType generated by hbm2java
 */
@Entity
@Table(name = "mst_worklist_type", catalog = "haaksquare_db")
public class MstWorklistType implements java.io.Serializable {

	private MstWorklistTypeId id;

	public MstWorklistType() {
	}

	public MstWorklistType(MstWorklistTypeId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "worklistTypeId", column = @Column(name = "worklist_type_id")),
			@AttributeOverride(name = "worklistTypeName", column = @Column(name = "worklist_type_name", length = 200)),
			@AttributeOverride(name = "modifyBy", column = @Column(name = "modify_by")),
			@AttributeOverride(name = "modifyDate", column = @Column(name = "modify_date", length = 19)),
			@AttributeOverride(name = "createBy", column = @Column(name = "create_by")),
			@AttributeOverride(name = "createDate", column = @Column(name = "create_date", length = 10)) })
	public MstWorklistTypeId getId() {
		return this.id;
	}

	public void setId(MstWorklistTypeId id) {
		this.id = id;
	}

}
