package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstWorklistStatus generated by hbm2java
 */
@Entity
@Table(name = "mst_worklist_status", catalog = "haaksquare_db")
public class MstWorklistStatus implements java.io.Serializable {

	private int worklistStatusId;
	private String worklistStatusName;
	private Integer modifyBy;
	private Date modifyDate;
	private Integer createBy;
	private Date createDate;

	public MstWorklistStatus() {
	}

	public MstWorklistStatus(int worklistStatusId) {
		this.worklistStatusId = worklistStatusId;
	}

	public MstWorklistStatus(int worklistStatusId, String worklistStatusName,
			Integer modifyBy, Date modifyDate, Integer createBy, Date createDate) {
		this.worklistStatusId = worklistStatusId;
		this.worklistStatusName = worklistStatusName;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "worklist_status_id", unique = true, nullable = false)
	public int getWorklistStatusId() {
		return this.worklistStatusId;
	}

	public void setWorklistStatusId(int worklistStatusId) {
		this.worklistStatusId = worklistStatusId;
	}

	@Column(name = "worklist_status_name", length = 100)
	public String getWorklistStatusName() {
		return this.worklistStatusName;
	}

	public void setWorklistStatusName(String worklistStatusName) {
		this.worklistStatusName = worklistStatusName;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
