package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SmsTo generated by hbm2java
 */
@Entity
@Table(name = "sms_to", catalog = "haaksquare_db")
public class SmsTo implements java.io.Serializable {

	private Integer smsToId;
	private int smsId;
	private int communityId;
	private int userId;
	private String mobileNo;
	private String smsStatus;
	private int smsCradit;
	private Date createDate;
	private int createBy;

	public SmsTo() {
	}

	public SmsTo(int smsId, int communityId, int userId, String mobileNo,
			String smsStatus, int smsCradit, Date createDate, int createBy) {
		this.smsId = smsId;
		this.communityId = communityId;
		this.userId = userId;
		this.mobileNo = mobileNo;
		this.smsStatus = smsStatus;
		this.smsCradit = smsCradit;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sms_to_id", unique = true, nullable = false)
	public Integer getSmsToId() {
		return this.smsToId;
	}

	public void setSmsToId(Integer smsToId) {
		this.smsToId = smsToId;
	}

	@Column(name = "sms_id", nullable = false)
	public int getSmsId() {
		return this.smsId;
	}

	public void setSmsId(int smsId) {
		this.smsId = smsId;
	}

	@Column(name = "community_id", nullable = false)
	public int getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(int communityId) {
		this.communityId = communityId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "mobile_no", nullable = false, length = 20)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "sms_status", nullable = false, length = 100)
	public String getSmsStatus() {
		return this.smsStatus;
	}

	public void setSmsStatus(String smsStatus) {
		this.smsStatus = smsStatus;
	}

	@Column(name = "sms_cradit", nullable = false)
	public int getSmsCradit() {
		return this.smsCradit;
	}

	public void setSmsCradit(int smsCradit) {
		this.smsCradit = smsCradit;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "create_by", nullable = false)
	public int getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(int createBy) {
		this.createBy = createBy;
	}

}
