package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VCommunityDashBoard generated by hbm2java
 */
@Entity
@Table(name = "v_community_dash_board", catalog = "haaksquare_db")
public class VCommunityDashBoard implements java.io.Serializable {

	private VCommunityDashBoardId id;

	public VCommunityDashBoard() {
	}

	public VCommunityDashBoard(VCommunityDashBoardId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "communityDashBoardId", column = @Column(name = "community_dash_board_id", nullable = false)),
			@AttributeOverride(name = "revenueAreasSquarePlan", column = @Column(name = "revenue_areas_square_plan", precision = 10, scale = 0)),
			@AttributeOverride(name = "revenueAreasSquareActual", column = @Column(name = "revenue_areas_square_actual", precision = 10, scale = 0)),
			@AttributeOverride(name = "revenueAreasAmountPlan", column = @Column(name = "revenue_areas_amount_plan", precision = 10, scale = 0)),
			@AttributeOverride(name = "revenueAreasAmountActual", column = @Column(name = "revenue_areas_amount_actual", precision = 10, scale = 0)),
			@AttributeOverride(name = "expensesAreasSquarePlan", column = @Column(name = "expenses_areas_square_plan", precision = 10, scale = 0)),
			@AttributeOverride(name = "expensesAreasSquareActual", column = @Column(name = "expenses_areas_square_actual", precision = 10, scale = 0)),
			@AttributeOverride(name = "expensesAreasAmountPlan", column = @Column(name = "expenses_areas_amount_plan", precision = 10, scale = 0)),
			@AttributeOverride(name = "expensesAreasAmountActual", column = @Column(name = "expenses_areas_amount_actual", precision = 10, scale = 0)),
			@AttributeOverride(name = "saveAmount", column = @Column(name = "save_amount", precision = 10, scale = 0)),
			@AttributeOverride(name = "paid", column = @Column(name = "paid")),
			@AttributeOverride(name = "notPaid", column = @Column(name = "not_paid")),
			@AttributeOverride(name = "modifyBy", column = @Column(name = "modify_by")),
			@AttributeOverride(name = "modifyDate", column = @Column(name = "modify_date", length = 19)),
			@AttributeOverride(name = "createBy", column = @Column(name = "create_by")),
			@AttributeOverride(name = "createDate", column = @Column(name = "create_date", length = 10)) })
	public VCommunityDashBoardId getId() {
		return this.id;
	}

	public void setId(VCommunityDashBoardId id) {
		this.id = id;
	}

}
