package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VCommunityMail generated by hbm2java
 */
@Entity
@Table(name = "v_community_mail", catalog = "haaksquare_db")
public class VCommunityMail implements java.io.Serializable {

	private VCommunityMailId id;

	public VCommunityMail() {
	}

	public VCommunityMail(VCommunityMailId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "communityMailId", column = @Column(name = "community_mail_id", nullable = false)),
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)),
			@AttributeOverride(name = "mailSeq", column = @Column(name = "mail_seq", nullable = false)),
			@AttributeOverride(name = "fromUserId", column = @Column(name = "from_user_id")),
			@AttributeOverride(name = "mailSubject", column = @Column(name = "mail_subject", length = 1000)),
			@AttributeOverride(name = "mailBody", column = @Column(name = "mail_body", length = 2000)),
			@AttributeOverride(name = "createDate", column = @Column(name = "create_date", length = 10)) })
	public VCommunityMailId getId() {
		return this.id;
	}

	public void setId(VCommunityMailId id) {
		this.id = id;
	}

}
