package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VCommunityAttachFileId generated by hbm2java
 */
@Embeddable
public class VCommunityAttachFileId implements java.io.Serializable {

	private String fileName;
	private String fileTypeName;
	private int communityId;

	public VCommunityAttachFileId() {
	}

	public VCommunityAttachFileId(String fileName, String fileTypeName,
			int communityId) {
		this.fileName = fileName;
		this.fileTypeName = fileTypeName;
		this.communityId = communityId;
	}

	@Column(name = "file_name", nullable = false, length = 200)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "file_type_name", nullable = false, length = 100)
	public String getFileTypeName() {
		return this.fileTypeName;
	}

	public void setFileTypeName(String fileTypeName) {
		this.fileTypeName = fileTypeName;
	}

	@Column(name = "community_id", nullable = false)
	public int getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(int communityId) {
		this.communityId = communityId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VCommunityAttachFileId))
			return false;
		VCommunityAttachFileId castOther = (VCommunityAttachFileId) other;

		return ((this.getFileName() == castOther.getFileName()) || (this
				.getFileName() != null && castOther.getFileName() != null && this
				.getFileName().equals(castOther.getFileName())))
				&& ((this.getFileTypeName() == castOther.getFileTypeName()) || (this
						.getFileTypeName() != null
						&& castOther.getFileTypeName() != null && this
						.getFileTypeName().equals(castOther.getFileTypeName())))
				&& (this.getCommunityId() == castOther.getCommunityId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFileName() == null ? 0 : this.getFileName().hashCode());
		result = 37
				* result
				+ (getFileTypeName() == null ? 0 : this.getFileTypeName()
						.hashCode());
		result = 37 * result + this.getCommunityId();
		return result;
	}

}
