package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VCommunityWhatNearByDetail generated by hbm2java
 */
@Entity
@Table(name = "v_community_what_near_by_detail", catalog = "haaksquare_db")
public class VCommunityWhatNearByDetail implements java.io.Serializable {

	private VCommunityWhatNearByDetailId id;

	public VCommunityWhatNearByDetail() {
	}

	public VCommunityWhatNearByDetail(VCommunityWhatNearByDetailId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "communityLifestyleId", column = @Column(name = "community_lifestyle_id", nullable = false)),
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)),
			@AttributeOverride(name = "lifestyleFullName", column = @Column(name = "lifestyle_full_name", length = 500)),
			@AttributeOverride(name = "distanceFromHoa", column = @Column(name = "distance_from_HOA", precision = 10)),
			@AttributeOverride(name = "lifestyleLink", column = @Column(name = "lifestyle_link", length = 300)),
			@AttributeOverride(name = "recommende", column = @Column(name = "recommende", length = 1000)),
			@AttributeOverride(name = "address", column = @Column(name = "address", length = 1000)),
			@AttributeOverride(name = "contractNo", column = @Column(name = "contract_no", length = 200)) })
	public VCommunityWhatNearByDetailId getId() {
		return this.id;
	}

	public void setId(VCommunityWhatNearByDetailId id) {
		this.id = id;
	}

}
