package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VCommunityWhatnearby generated by hbm2java
 */
@Entity
@Table(name = "v_community_whatnearby", catalog = "haaksquare_db")
public class VCommunityWhatnearby implements java.io.Serializable {

	private VCommunityWhatnearbyId id;

	public VCommunityWhatnearby() {
	}

	public VCommunityWhatnearby(VCommunityWhatnearbyId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "communityLifestyleId", column = @Column(name = "community_lifestyle_id", nullable = false)),
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)),
			@AttributeOverride(name = "lifestyleName", column = @Column(name = "lifestyle_name", length = 500)),
			@AttributeOverride(name = "fileName", column = @Column(name = "file_name", nullable = false, length = 200)),
			@AttributeOverride(name = "pathName", column = @Column(name = "path_name", nullable = false, length = 200)),
			@AttributeOverride(name = "attachId", column = @Column(name = "attach_id", nullable = false)),
			@AttributeOverride(name = "attachSeq", column = @Column(name = "attach_seq", nullable = false)),
			@AttributeOverride(name = "lifestyleUrl", column = @Column(name = "lifestyle_url", length = 1000)),
			@AttributeOverride(name = "lifestyleGoogleMap", column = @Column(name = "lifestyle_google_map", length = 1000)),
			@AttributeOverride(name = "lifestyleDetail", column = @Column(name = "lifestyle_detail", length = 1000)) })
	public VCommunityWhatnearbyId getId() {
		return this.id;
	}

	public void setId(VCommunityWhatnearbyId id) {
		this.id = id;
	}

}
