package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VCommunityNews generated by hbm2java
 */
@Entity
@Table(name = "v_community_news", catalog = "haaksquare_db")
public class VCommunityNews implements java.io.Serializable {

	private VCommunityNewsId id;

	public VCommunityNews() {
	}

	public VCommunityNews(VCommunityNewsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "communityNewId", column = @Column(name = "community_new_id", nullable = false)),
			@AttributeOverride(name = "fgPublic", column = @Column(name = "fg_public", length = 1)),
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)),
			@AttributeOverride(name = "newSeq", column = @Column(name = "new_seq", nullable = false)),
			@AttributeOverride(name = "newSubject", column = @Column(name = "new_subject", length = 1000)),
			@AttributeOverride(name = "newDetail", column = @Column(name = "new_detail", length = 2000)),
			@AttributeOverride(name = "lifestyleLink", column = @Column(name = "lifestyle_link", length = 300)),
			@AttributeOverride(name = "lifestyleUrl", column = @Column(name = "lifestyle_url", length = 1000)),
			@AttributeOverride(name = "lifestyleGoogleMap", column = @Column(name = "lifestyle_google_map", length = 1000)),
			@AttributeOverride(name = "googleMapLatitude", column = @Column(name = "google_map_latitude", length = 500)),
			@AttributeOverride(name = "googleMapLongtitude", column = @Column(name = "google_map_longtitude", length = 500)),
			@AttributeOverride(name = "googleMapUrl", column = @Column(name = "google_map_url", length = 500)),
			@AttributeOverride(name = "createBy", column = @Column(name = "create_by")),
			@AttributeOverride(name = "createDate", column = @Column(name = "create_date", length = 10)),
			@AttributeOverride(name = "fromSource", column = @Column(name = "from_source", length = 1000)) })
	public VCommunityNewsId getId() {
		return this.id;
	}

	public void setId(VCommunityNewsId id) {
		this.id = id;
	}

}
