package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VCommunityNewsPicture generated by hbm2java
 */
@Entity
@Table(name = "v_community_news_picture", catalog = "haaksquare_db")
public class VCommunityNewsPicture implements java.io.Serializable {

	private VCommunityNewsPictureId id;

	public VCommunityNewsPicture() {
	}

	public VCommunityNewsPicture(VCommunityNewsPictureId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "fileName", column = @Column(name = "file_name", nullable = false, length = 200)),
			@AttributeOverride(name = "pathName", column = @Column(name = "path_name", nullable = false, length = 200)),
			@AttributeOverride(name = "fileDetail", column = @Column(name = "file_detail", nullable = false, length = 2000)),
			@AttributeOverride(name = "attachUrl", column = @Column(name = "attach_url", nullable = false, length = 200)),
			@AttributeOverride(name = "attachSeq", column = @Column(name = "attach_seq", nullable = false)) })
	public VCommunityNewsPictureId getId() {
		return this.id;
	}

	public void setId(VCommunityNewsPictureId id) {
		this.id = id;
	}

}
