package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VCommunityDetail generated by hbm2java
 */
@Entity
@Table(name = "v_community_detail", catalog = "haaksquare_db")
public class VCommunityDetail implements java.io.Serializable {

	private VCommunityDetailId id;

	public VCommunityDetail() {
	}

	public VCommunityDetail(VCommunityDetailId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)),
			@AttributeOverride(name = "communityName", column = @Column(name = "community_name", length = 200)),
			@AttributeOverride(name = "communitySize", column = @Column(name = "community_size", length = 100)),
			@AttributeOverride(name = "companyOwner", column = @Column(name = "company_owner", length = 200)),
			@AttributeOverride(name = "startPrise", column = @Column(name = "start_prise", precision = 10, scale = 0)),
			@AttributeOverride(name = "endPrise", column = @Column(name = "end_prise", precision = 10, scale = 0)),
			@AttributeOverride(name = "addressId", column = @Column(name = "address_id")),
			@AttributeOverride(name = "addressNo", column = @Column(name = "address_no", length = 1000)),
			@AttributeOverride(name = "soi", column = @Column(name = "soi", length = 200)),
			@AttributeOverride(name = "moo", column = @Column(name = "moo", length = 200)),
			@AttributeOverride(name = "road", column = @Column(name = "road", length = 200)),
			@AttributeOverride(name = "state", column = @Column(name = "state", length = 200)),
			@AttributeOverride(name = "zipcode", column = @Column(name = "zipcode", length = 10)),
			@AttributeOverride(name = "country", column = @Column(name = "country", length = 200)),
			@AttributeOverride(name = "telephone", column = @Column(name = "telephone", length = 100)),
			@AttributeOverride(name = "mobile", column = @Column(name = "mobile", length = 100)),
			@AttributeOverride(name = "communityTypeName", column = @Column(name = "community_type_name")),
			@AttributeOverride(name = "provinceId", column = @Column(name = "province_id", length = 10)),
			@AttributeOverride(name = "provinceName", column = @Column(name = "province_name")),
			@AttributeOverride(name = "amphoeName", column = @Column(name = "amphoe_name")),
			@AttributeOverride(name = "tumbolName", column = @Column(name = "tumbol_name", length = 100)),
			@AttributeOverride(name = "amphoeId", column = @Column(name = "amphoe_id", length = 10)),
			@AttributeOverride(name = "googleMapLatitude", column = @Column(name = "google_map_latitude", length = 500)),
			@AttributeOverride(name = "googleMapLongtitude", column = @Column(name = "google_map_longtitude", length = 500)),
			@AttributeOverride(name = "googleMapUrl", column = @Column(name = "google_map_url", length = 500)),
			@AttributeOverride(name = "fileName", column = @Column(name = "file_name", nullable = false, length = 200)),
			@AttributeOverride(name = "pathName", column = @Column(name = "path_name", nullable = false, length = 200)),
			@AttributeOverride(name = "fileDetail", column = @Column(name = "file_detail", nullable = false, length = 2000)),
			@AttributeOverride(name = "fileTypeName", column = @Column(name = "file_type_name", nullable = false, length = 100)) })
	public VCommunityDetailId getId() {
		return this.id;
	}

	public void setId(VCommunityDetailId id) {
		this.id = id;
	}

}
