package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VMenu generated by hbm2java
 */
@Entity
@Table(name = "v_menu", catalog = "haaksquare_db")
public class VMenu implements java.io.Serializable {

	private VMenuId id;

	public VMenu() {
	}

	public VMenu(VMenuId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "menuName", column = @Column(name = "menu_name", length = 100)),
			@AttributeOverride(name = "menuUrl", column = @Column(name = "menu_url", nullable = false, length = 100)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)),
			@AttributeOverride(name = "menuImageUrl", column = @Column(name = "menu_image_url", length = 100)),
			@AttributeOverride(name = "menuId", column = @Column(name = "menu_id", nullable = false)),
			@AttributeOverride(name = "packageId", column = @Column(name = "package_id", nullable = false)),
			@AttributeOverride(name = "seq", column = @Column(name = "seq")) })
	public VMenuId getId() {
		return this.id;
	}

	public void setId(VMenuId id) {
		this.id = id;
	}

}
