package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VMenuPermission generated by hbm2java
 */
@Entity
@Table(name = "v_menu_permission", catalog = "haaksquare_db")
public class VMenuPermission implements java.io.Serializable {

	private VMenuPermissionId id;

	public VMenuPermission() {
	}

	public VMenuPermission(VMenuPermissionId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "menuId", column = @Column(name = "menu_id", nullable = false)),
			@AttributeOverride(name = "menuName", column = @Column(name = "menu_name", length = 100)),
			@AttributeOverride(name = "seq", column = @Column(name = "seq")),
			@AttributeOverride(name = "levelMenu", column = @Column(name = "level_menu")),
			@AttributeOverride(name = "seqSub", column = @Column(name = "seq_sub")),
			@AttributeOverride(name = "parrentSubMenu", column = @Column(name = "parrent_sub_menu")),
			@AttributeOverride(name = "roleModuleActionId", column = @Column(name = "role_module_action_id", nullable = false)),
			@AttributeOverride(name = "packageId", column = @Column(name = "package_id")),
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id")),
			@AttributeOverride(name = "roleId", column = @Column(name = "role_id")),
			@AttributeOverride(name = "fgView", column = @Column(name = "fg_view", length = 1)),
			@AttributeOverride(name = "fgAdd", column = @Column(name = "fg_Add", length = 1)),
			@AttributeOverride(name = "fgEdit", column = @Column(name = "fg_edit", length = 1)),
			@AttributeOverride(name = "fgDelete", column = @Column(name = "fg_delete", length = 1)),
			@AttributeOverride(name = "modifyBy", column = @Column(name = "modify_by")),
			@AttributeOverride(name = "modyfyDate", column = @Column(name = "modyfy_date", length = 19)),
			@AttributeOverride(name = "createBy", column = @Column(name = "create_by")),
			@AttributeOverride(name = "createDate", column = @Column(name = "create_date", length = 19)) })
	public VMenuPermissionId getId() {
		return this.id;
	}

	public void setId(VMenuPermissionId id) {
		this.id = id;
	}

}
