package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VModue generated by hbm2java
 */
@Entity
@Table(name = "v_modue", catalog = "haaksquare_db")
public class VModue implements java.io.Serializable {

	private VModueId id;

	public VModue() {
	}

	public VModue(VModueId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "packageName", column = @Column(name = "package_name", length = 200)),
			@AttributeOverride(name = "menuName", column = @Column(name = "menu_name", length = 100)),
			@AttributeOverride(name = "moduleName", column = @Column(name = "module_name", length = 200)),
			@AttributeOverride(name = "packageId", column = @Column(name = "package_id", nullable = false)),
			@AttributeOverride(name = "menuId", column = @Column(name = "menu_id", nullable = false)),
			@AttributeOverride(name = "moduleId", column = @Column(name = "module_id", nullable = false)),
			@AttributeOverride(name = "packageMenuId", column = @Column(name = "package_menu_id", nullable = false)),
			@AttributeOverride(name = "moduleUrl", column = @Column(name = "module_url", length = 100)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)),
			@AttributeOverride(name = "moduleImageUrl", column = @Column(name = "module_image_url", length = 100)),
			@AttributeOverride(name = "moduleDetail", column = @Column(name = "module_detail", length = 1000)) })
	public VModueId getId() {
		return this.id;
	}

	public void setId(VModueId id) {
		this.id = id;
	}

}
