package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VSmsemailProfiles generated by hbm2java
 */
@Entity
@Table(name = "v_smsemail_profiles", catalog = "haaksquare_db")
public class VSmsemailProfiles implements java.io.Serializable {

	private VSmsemailProfilesId id;

	public VSmsemailProfiles() {
	}

	public VSmsemailProfiles(VSmsemailProfilesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "addressId", column = @Column(name = "address_id", nullable = false)),
			@AttributeOverride(name = "addressNo", column = @Column(name = "address_no", length = 1000)),
			@AttributeOverride(name = "soi", column = @Column(name = "soi", length = 200)),
			@AttributeOverride(name = "moo", column = @Column(name = "moo", length = 200)),
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)),
			@AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", nullable = false, length = 20)),
			@AttributeOverride(name = "road", column = @Column(name = "road", length = 200)),
			@AttributeOverride(name = "email", column = @Column(name = "email", length = 100)),
			@AttributeOverride(name = "mobile", column = @Column(name = "mobile", length = 100)) })
	public VSmsemailProfilesId getId() {
		return this.id;
	}

	public void setId(VSmsemailProfilesId id) {
		this.id = id;
	}

}
