package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VUserAction generated by hbm2java
 */
@Entity
@Table(name = "v_user_action", catalog = "haaksquare_db")
public class VUserAction implements java.io.Serializable {

	private VUserActionId id;

	public VUserAction() {
	}

	public VUserAction(VUserActionId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "packageName", column = @Column(name = "package_name", length = 200)),
			@AttributeOverride(name = "menuName", column = @Column(name = "menu_name", length = 100)),
			@AttributeOverride(name = "moduleName", column = @Column(name = "module_name", length = 200)),
			@AttributeOverride(name = "packageId", column = @Column(name = "package_id", nullable = false)),
			@AttributeOverride(name = "menuId", column = @Column(name = "menu_id", nullable = false)),
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)),
			@AttributeOverride(name = "firstName", column = @Column(name = "first_name", nullable = false, length = 200)),
			@AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", nullable = false, length = 20)),
			@AttributeOverride(name = "lastName", column = @Column(name = "last_name", length = 200)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "pass", column = @Column(name = "pass", nullable = false, length = 10)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)),
			@AttributeOverride(name = "moduleId", column = @Column(name = "module_id", nullable = false)) })
	public VUserActionId getId() {
		return this.id;
	}

	public void setId(VUserActionId id) {
		this.id = id;
	}

}
