package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VUserDetailImg generated by hbm2java
 */
@Entity
@Table(name = "v_user_detail_img", catalog = "haaksquare_db")
public class VUserDetailImg implements java.io.Serializable {

	private VUserDetailImgId id;

	public VUserDetailImg() {
	}

	public VUserDetailImg(VUserDetailImgId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", nullable = false, length = 20)),
			@AttributeOverride(name = "firstName", column = @Column(name = "first_name", nullable = false, length = 200)),
			@AttributeOverride(name = "lastName", column = @Column(name = "last_name", length = 200)),
			@AttributeOverride(name = "nickName", column = @Column(name = "nick_name", length = 100)),
			@AttributeOverride(name = "email", column = @Column(name = "email", length = 100)),
			@AttributeOverride(name = "mobileNo", column = @Column(name = "mobile_no", length = 200)),
			@AttributeOverride(name = "faxNo", column = @Column(name = "fax_no", length = 200)),
			@AttributeOverride(name = "telephoneNo", column = @Column(name = "telephone_no", length = 200)),
			@AttributeOverride(name = "sports", column = @Column(name = "sports", length = 200)),
			@AttributeOverride(name = "hobbies", column = @Column(name = "hobbies", length = 200)),
			@AttributeOverride(name = "profession", column = @Column(name = "profession", length = 200)),
			@AttributeOverride(name = "addressId", column = @Column(name = "address_id", nullable = false)),
			@AttributeOverride(name = "attachId", column = @Column(name = "attach_id", nullable = false)),
			@AttributeOverride(name = "linkId", column = @Column(name = "link_id", nullable = false)),
			@AttributeOverride(name = "attachSeq", column = @Column(name = "attach_seq", nullable = false)),
			@AttributeOverride(name = "fileTypeId", column = @Column(name = "file_type_id", nullable = false)),
			@AttributeOverride(name = "fileName", column = @Column(name = "file_name", nullable = false, length = 200)),
			@AttributeOverride(name = "pathName", column = @Column(name = "path_name", nullable = false, length = 200)),
			@AttributeOverride(name = "fileDetail", column = @Column(name = "file_detail", nullable = false, length = 2000)),
			@AttributeOverride(name = "attachUrl", column = @Column(name = "attach_url", nullable = false, length = 200)),
			@AttributeOverride(name = "modifyBy", column = @Column(name = "modify_by")),
			@AttributeOverride(name = "modifyDate", column = @Column(name = "modify_date", length = 19)),
			@AttributeOverride(name = "createBy", column = @Column(name = "create_by")),
			@AttributeOverride(name = "createDate", column = @Column(name = "create_date", length = 10)) })
	public VUserDetailImgId getId() {
		return this.id;
	}

	public void setId(VUserDetailImgId id) {
		this.id = id;
	}

}
