package com.haak.haaksq.autogen;

// Generated Feb 13, 2013 12:10:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WorklistId generated by hbm2java
 */
@Embeddable
public class WorklistId implements java.io.Serializable {

	private int worklistId;
	private int worklistSeq;

	public WorklistId() {
	}

	public WorklistId(int worklistId, int worklistSeq) {
		this.worklistId = worklistId;
		this.worklistSeq = worklistSeq;
	}

	@Column(name = "worklist_id", nullable = false)
	public int getWorklistId() {
		return this.worklistId;
	}

	public void setWorklistId(int worklistId) {
		this.worklistId = worklistId;
	}

	@Column(name = "worklist_seq", nullable = false)
	public int getWorklistSeq() {
		return this.worklistSeq;
	}

	public void setWorklistSeq(int worklistSeq) {
		this.worklistSeq = worklistSeq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WorklistId))
			return false;
		WorklistId castOther = (WorklistId) other;

		return (this.getWorklistId() == castOther.getWorklistId())
				&& (this.getWorklistSeq() == castOther.getWorklistSeq());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWorklistId();
		result = 37 * result + this.getWorklistSeq();
		return result;
	}

}
