package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "activity", catalog = "haaksquare_db")
public class Activity implements java.io.Serializable {

	private ActivityId id;

	public Activity() {
	}

	public Activity(ActivityId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "moduleActivityId", column = @Column(name = "module_activity_id")),
			@AttributeOverride(name = "activityId", column = @Column(name = "activity_id", nullable = false)),
			@AttributeOverride(name = "moduleId", column = @Column(name = "module_id", nullable = false)),
			@AttributeOverride(name = "activityTypeId", column = @Column(name = "activity_type_id", nullable = false)),
			@AttributeOverride(name = "activityName", column = @Column(name = "activity_name", nullable = false, length = 200)),
			@AttributeOverride(name = "activityDetail", column = @Column(name = "activity_detail", length = 2000)),
			@AttributeOverride(name = "activityDate", column = @Column(name = "activity_date", length = 19)),
			@AttributeOverride(name = "modifyBy", column = @Column(name = "modify_by")),
			@AttributeOverride(name = "modifyDate", column = @Column(name = "modify_date", length = 19)),
			@AttributeOverride(name = "createBy", column = @Column(name = "create_by")),
			@AttributeOverride(name = "createDate", column = @Column(name = "create_date", length = 19)) })
	public ActivityId getId() {
		return this.id;
	}

	public void setId(ActivityId id) {
		this.id = id;
	}

}
