package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CommunityAmenities generated by hbm2java
 */
@Entity
@Table(name = "community_amenities", catalog = "haaksquare_db")
public class CommunityAmenities implements java.io.Serializable {

	private int communityAmenitiesId;
	private Integer communityId;
	private Integer amenitiesTypeId;
	private String amenitiesFg;
	private String amenitiesDetail;
	private Integer modifyBy;
	private Date modifyDate;
	private Integer createBy;
	private Date createDate;

	public CommunityAmenities() {
	}

	public CommunityAmenities(int communityAmenitiesId) {
		this.communityAmenitiesId = communityAmenitiesId;
	}

	public CommunityAmenities(int communityAmenitiesId, Integer communityId,
			Integer amenitiesTypeId, String amenitiesFg,
			String amenitiesDetail, Integer modifyBy, Date modifyDate,
			Integer createBy, Date createDate) {
		this.communityAmenitiesId = communityAmenitiesId;
		this.communityId = communityId;
		this.amenitiesTypeId = amenitiesTypeId;
		this.amenitiesFg = amenitiesFg;
		this.amenitiesDetail = amenitiesDetail;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "community_amenities_id", unique = true, nullable = false)
	public int getCommunityAmenitiesId() {
		return this.communityAmenitiesId;
	}

	public void setCommunityAmenitiesId(int communityAmenitiesId) {
		this.communityAmenitiesId = communityAmenitiesId;
	}

	@Column(name = "community_id")
	public Integer getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(Integer communityId) {
		this.communityId = communityId;
	}

	@Column(name = "amenities_type_id")
	public Integer getAmenitiesTypeId() {
		return this.amenitiesTypeId;
	}

	public void setAmenitiesTypeId(Integer amenitiesTypeId) {
		this.amenitiesTypeId = amenitiesTypeId;
	}

	@Column(name = "amenities_fg", length = 1)
	public String getAmenitiesFg() {
		return this.amenitiesFg;
	}

	public void setAmenitiesFg(String amenitiesFg) {
		this.amenitiesFg = amenitiesFg;
	}

	@Column(name = "amenities_detail", length = 500)
	public String getAmenitiesDetail() {
		return this.amenitiesDetail;
	}

	public void setAmenitiesDetail(String amenitiesDetail) {
		this.amenitiesDetail = amenitiesDetail;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
