package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MenuModuleId generated by hbm2java
 */
@Embeddable
public class MenuModuleId implements java.io.Serializable {

	private int menuModuleId;
	private int packageMenuId;
	private int menuId;

	public MenuModuleId() {
	}

	public MenuModuleId(int menuModuleId, int packageMenuId, int menuId) {
		this.menuModuleId = menuModuleId;
		this.packageMenuId = packageMenuId;
		this.menuId = menuId;
	}

	@Column(name = "menu_module_id", nullable = false)
	public int getMenuModuleId() {
		return this.menuModuleId;
	}

	public void setMenuModuleId(int menuModuleId) {
		this.menuModuleId = menuModuleId;
	}

	@Column(name = "package_menu_id", nullable = false)
	public int getPackageMenuId() {
		return this.packageMenuId;
	}

	public void setPackageMenuId(int packageMenuId) {
		this.packageMenuId = packageMenuId;
	}

	@Column(name = "menu_id", nullable = false)
	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MenuModuleId))
			return false;
		MenuModuleId castOther = (MenuModuleId) other;

		return (this.getMenuModuleId() == castOther.getMenuModuleId())
				&& (this.getPackageMenuId() == castOther.getPackageMenuId())
				&& (this.getMenuId() == castOther.getMenuId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMenuModuleId();
		result = 37 * result + this.getPackageMenuId();
		result = 37 * result + this.getMenuId();
		return result;
	}

}
