package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModulePackage generated by hbm2java
 */
@Entity
@Table(name = "module_package", catalog = "haaksquare_db")
public class ModulePackage implements java.io.Serializable {

	private ModulePackageId id;

	public ModulePackage() {
	}

	public ModulePackage(ModulePackageId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "moduleId", column = @Column(name = "module_id", nullable = false)),
			@AttributeOverride(name = "packageId", column = @Column(name = "package_id", nullable = false)) })
	public ModulePackageId getId() {
		return this.id;
	}

	public void setId(ModulePackageId id) {
		this.id = id;
	}

}
