package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstAmphoeId generated by hbm2java
 */
@Embeddable
public class MstAmphoeId implements java.io.Serializable {

	private String amphoeId;
	private int languageId;

	public MstAmphoeId() {
	}

	public MstAmphoeId(String amphoeId, int languageId) {
		this.amphoeId = amphoeId;
		this.languageId = languageId;
	}

	@Column(name = "amphoe_id", nullable = false)
	public String getAmphoeId() {
		return this.amphoeId;
	}

	public void setAmphoeId(String amphoeId) {
		this.amphoeId = amphoeId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MstAmphoeId))
			return false;
		MstAmphoeId castOther = (MstAmphoeId) other;

		return ((this.getAmphoeId() == castOther.getAmphoeId()) || (this
				.getAmphoeId() != null && castOther.getAmphoeId() != null && this
				.getAmphoeId().equals(castOther.getAmphoeId())))
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAmphoeId() == null ? 0 : this.getAmphoeId().hashCode());
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
