package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstAd generated by hbm2java
 */
@Entity
@Table(name = "mst_ad", catalog = "haaksquare_db")
public class MstAd implements java.io.Serializable {

	private int adId;
	private Integer adSeq;
	private Integer adFileTypeId;
	private String adFilename;
	private String adPath;
	private String adUrl;
	private String fgPublic;
	private Integer modifyBy;
	private Date modifyDate;
	private Integer createBy;
	private Date createDate;

	public MstAd() {
	}

	public MstAd(int adId) {
		this.adId = adId;
	}

	public MstAd(int adId, Integer adSeq, Integer adFileTypeId,
			String adFilename, String adPath, String adUrl, String fgPublic,
			Integer modifyBy, Date modifyDate, Integer createBy, Date createDate) {
		this.adId = adId;
		this.adSeq = adSeq;
		this.adFileTypeId = adFileTypeId;
		this.adFilename = adFilename;
		this.adPath = adPath;
		this.adUrl = adUrl;
		this.fgPublic = fgPublic;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "ad_id", unique = true, nullable = false)
	public int getAdId() {
		return this.adId;
	}

	public void setAdId(int adId) {
		this.adId = adId;
	}

	@Column(name = "ad_seq")
	public Integer getAdSeq() {
		return this.adSeq;
	}

	public void setAdSeq(Integer adSeq) {
		this.adSeq = adSeq;
	}

	@Column(name = "ad_file_type_id")
	public Integer getAdFileTypeId() {
		return this.adFileTypeId;
	}

	public void setAdFileTypeId(Integer adFileTypeId) {
		this.adFileTypeId = adFileTypeId;
	}

	@Column(name = "ad_filename", length = 500)
	public String getAdFilename() {
		return this.adFilename;
	}

	public void setAdFilename(String adFilename) {
		this.adFilename = adFilename;
	}

	@Column(name = "ad_path", length = 500)
	public String getAdPath() {
		return this.adPath;
	}

	public void setAdPath(String adPath) {
		this.adPath = adPath;
	}

	@Column(name = "ad_url", length = 1000)
	public String getAdUrl() {
		return this.adUrl;
	}

	public void setAdUrl(String adUrl) {
		this.adUrl = adUrl;
	}

	@Column(name = "fg_public", length = 1)
	public String getFgPublic() {
		return this.fgPublic;
	}

	public void setFgPublic(String fgPublic) {
		this.fgPublic = fgPublic;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
