package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstAdFileType generated by hbm2java
 */
@Entity
@Table(name = "mst_ad_file_type", catalog = "haaksquare_db")
public class MstAdFileType implements java.io.Serializable {

	private int adFileTypeId;
	private String adFileTypeName;
	private Integer modifyBy;
	private Date modifyDate;
	private Integer createBy;
	private Date createDate;

	public MstAdFileType() {
	}

	public MstAdFileType(int adFileTypeId) {
		this.adFileTypeId = adFileTypeId;
	}

	public MstAdFileType(int adFileTypeId, String adFileTypeName,
			Integer modifyBy, Date modifyDate, Integer createBy, Date createDate) {
		this.adFileTypeId = adFileTypeId;
		this.adFileTypeName = adFileTypeName;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "ad_file_type_id", unique = true, nullable = false)
	public int getAdFileTypeId() {
		return this.adFileTypeId;
	}

	public void setAdFileTypeId(int adFileTypeId) {
		this.adFileTypeId = adFileTypeId;
	}

	@Column(name = "ad_file_type_name", length = 100)
	public String getAdFileTypeName() {
		return this.adFileTypeName;
	}

	public void setAdFileTypeName(String adFileTypeName) {
		this.adFileTypeName = adFileTypeName;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
