package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MstCommunityTypeId generated by hbm2java
 */
@Embeddable
public class MstCommunityTypeId implements java.io.Serializable {

	private int communityTypeId;
	private int languageId;

	public MstCommunityTypeId() {
	}

	public MstCommunityTypeId(int communityTypeId, int languageId) {
		this.communityTypeId = communityTypeId;
		this.languageId = languageId;
	}

	@Column(name = "community_type_id", nullable = false)
	public int getCommunityTypeId() {
		return this.communityTypeId;
	}

	public void setCommunityTypeId(int communityTypeId) {
		this.communityTypeId = communityTypeId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MstCommunityTypeId))
			return false;
		MstCommunityTypeId castOther = (MstCommunityTypeId) other;

		return (this.getCommunityTypeId() == castOther.getCommunityTypeId())
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCommunityTypeId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
