package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstModule generated by hbm2java
 */
@Entity
@Table(name = "mst_module", catalog = "haaksquare_db")
public class MstModule implements java.io.Serializable {

	private MstModuleId id;
	private String moduleName;
	private String moduleDetail;
	private String freamPosition;
	private String moduleImageUrl;
	private String moduleUrl;
	private Integer modifyBy;
	private Date modifyDate;
	private Integer createBy;
	private Date createDate;

	public MstModule() {
	}

	public MstModule(MstModuleId id) {
		this.id = id;
	}

	public MstModule(MstModuleId id, String moduleName, String moduleDetail,
			String freamPosition, String moduleImageUrl, String moduleUrl,
			Integer modifyBy, Date modifyDate, Integer createBy, Date createDate) {
		this.id = id;
		this.moduleName = moduleName;
		this.moduleDetail = moduleDetail;
		this.freamPosition = freamPosition;
		this.moduleImageUrl = moduleImageUrl;
		this.moduleUrl = moduleUrl;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.createDate = createDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "moduleId", column = @Column(name = "module_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public MstModuleId getId() {
		return this.id;
	}

	public void setId(MstModuleId id) {
		this.id = id;
	}

	@Column(name = "module_name", length = 200)
	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	@Column(name = "module_detail", length = 1000)
	public String getModuleDetail() {
		return this.moduleDetail;
	}

	public void setModuleDetail(String moduleDetail) {
		this.moduleDetail = moduleDetail;
	}

	@Column(name = "fream_position", length = 20)
	public String getFreamPosition() {
		return this.freamPosition;
	}

	public void setFreamPosition(String freamPosition) {
		this.freamPosition = freamPosition;
	}

	@Column(name = "module_image_url", length = 100)
	public String getModuleImageUrl() {
		return this.moduleImageUrl;
	}

	public void setModuleImageUrl(String moduleImageUrl) {
		this.moduleImageUrl = moduleImageUrl;
	}

	@Column(name = "module_url", length = 100)
	public String getModuleUrl() {
		return this.moduleUrl;
	}

	public void setModuleUrl(String moduleUrl) {
		this.moduleUrl = moduleUrl;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
