package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstSubject generated by hbm2java
 */
@Entity
@Table(name = "mst_subject", catalog = "haaksquare_db")
public class MstSubject implements java.io.Serializable {

	private int subjectId;
	private Integer subjectSeq;
	private String subjectName;
	private Integer roleId;
	private String publicFg;
	private Integer communityId;
	private Integer createBy;
	private Date createDate;
	private Integer modyfyBy;
	private Date modifyDate;

	public MstSubject() {
	}

	public MstSubject(int subjectId) {
		this.subjectId = subjectId;
	}

	public MstSubject(int subjectId, Integer subjectSeq, String subjectName,
			Integer roleId, String publicFg, Integer communityId,
			Integer createBy, Date createDate, Integer modyfyBy, Date modifyDate) {
		this.subjectId = subjectId;
		this.subjectSeq = subjectSeq;
		this.subjectName = subjectName;
		this.roleId = roleId;
		this.publicFg = publicFg;
		this.communityId = communityId;
		this.createBy = createBy;
		this.createDate = createDate;
		this.modyfyBy = modyfyBy;
		this.modifyDate = modifyDate;
	}

	@Id
	@Column(name = "subject_id", unique = true, nullable = false)
	public int getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(int subjectId) {
		this.subjectId = subjectId;
	}

	@Column(name = "subject_seq")
	public Integer getSubjectSeq() {
		return this.subjectSeq;
	}

	public void setSubjectSeq(Integer subjectSeq) {
		this.subjectSeq = subjectSeq;
	}

	@Column(name = "subject_name", length = 200)
	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	@Column(name = "role_id")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "public_fg", length = 1)
	public String getPublicFg() {
		return this.publicFg;
	}

	public void setPublicFg(String publicFg) {
		this.publicFg = publicFg;
	}

	@Column(name = "community_id")
	public Integer getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(Integer communityId) {
		this.communityId = communityId;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "modyfy_by")
	public Integer getModyfyBy() {
		return this.modyfyBy;
	}

	public void setModyfyBy(Integer modyfyBy) {
		this.modyfyBy = modyfyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
