package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstSmsType generated by hbm2java
 */
@Entity
@Table(name = "mst_sms_type", catalog = "haaksquare_db")
public class MstSmsType implements java.io.Serializable {

	private int smsTypeId;
	private String smsTypeName;
	private Integer modifyBy;
	private Date modifyDate;
	private Integer createBy;
	private Date createDate;

	public MstSmsType() {
	}

	public MstSmsType(int smsTypeId, String smsTypeName) {
		this.smsTypeId = smsTypeId;
		this.smsTypeName = smsTypeName;
	}

	public MstSmsType(int smsTypeId, String smsTypeName, Integer modifyBy,
			Date modifyDate, Integer createBy, Date createDate) {
		this.smsTypeId = smsTypeId;
		this.smsTypeName = smsTypeName;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "sms_type_id", unique = true, nullable = false)
	public int getSmsTypeId() {
		return this.smsTypeId;
	}

	public void setSmsTypeId(int smsTypeId) {
		this.smsTypeId = smsTypeId;
	}

	@Column(name = "sms_type_name", nullable = false, length = 100)
	public String getSmsTypeName() {
		return this.smsTypeName;
	}

	public void setSmsTypeName(String smsTypeName) {
		this.smsTypeName = smsTypeName;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
