package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstWorklistSubject generated by hbm2java
 */
@Entity
@Table(name = "mst_worklist_subject", catalog = "haaksquare_db")
public class MstWorklistSubject implements java.io.Serializable {

	private MstWorklistSubjectId id;
	private String worklistSubjectName;
	private Integer communityId;
	private String fgShowQuestName;
	private String fgShowAnswerName;
	private String fgPublic;
	private Integer modifyBy;
	private Date modifyDate;
	private Integer createBy;
	private Date createDate;

	public MstWorklistSubject() {
	}

	public MstWorklistSubject(MstWorklistSubjectId id) {
		this.id = id;
	}

	public MstWorklistSubject(MstWorklistSubjectId id,
			String worklistSubjectName, Integer communityId,
			String fgShowQuestName, String fgShowAnswerName, String fgPublic,
			Integer modifyBy, Date modifyDate, Integer createBy, Date createDate) {
		this.id = id;
		this.worklistSubjectName = worklistSubjectName;
		this.communityId = communityId;
		this.fgShowQuestName = fgShowQuestName;
		this.fgShowAnswerName = fgShowAnswerName;
		this.fgPublic = fgPublic;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.createDate = createDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "worklistSubjectId", column = @Column(name = "worklist_subject_id", nullable = false)),
			@AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false)) })
	public MstWorklistSubjectId getId() {
		return this.id;
	}

	public void setId(MstWorklistSubjectId id) {
		this.id = id;
	}

	@Column(name = "worklist_subject_name", length = 200)
	public String getWorklistSubjectName() {
		return this.worklistSubjectName;
	}

	public void setWorklistSubjectName(String worklistSubjectName) {
		this.worklistSubjectName = worklistSubjectName;
	}

	@Column(name = "community_id")
	public Integer getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(Integer communityId) {
		this.communityId = communityId;
	}

	@Column(name = "fg_show_quest_name", length = 1)
	public String getFgShowQuestName() {
		return this.fgShowQuestName;
	}

	public void setFgShowQuestName(String fgShowQuestName) {
		this.fgShowQuestName = fgShowQuestName;
	}

	@Column(name = "fg_show_answer_name", length = 1)
	public String getFgShowAnswerName() {
		return this.fgShowAnswerName;
	}

	public void setFgShowAnswerName(String fgShowAnswerName) {
		this.fgShowAnswerName = fgShowAnswerName;
	}

	@Column(name = "fg_public", length = 1)
	public String getFgPublic() {
		return this.fgPublic;
	}

	public void setFgPublic(String fgPublic) {
		this.fgPublic = fgPublic;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_date", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
