package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RoleModuleAction generated by hbm2java
 */
@Entity
@Table(name = "role_module_action", catalog = "haaksquare_db")
public class RoleModuleAction implements java.io.Serializable {

	private int roleModuleActionId;
	private Integer packageId;
	private Integer communityId;
	private Integer roleId;
	private Integer moduleId;
	private String fgView;
	private String fgAdd;
	private String fgEdit;
	private String fgDelete;
	private Integer modifyBy;
	private Date modyfyDate;
	private Integer createBy;
	private Date createDate;

	public RoleModuleAction() {
	}

	public RoleModuleAction(int roleModuleActionId) {
		this.roleModuleActionId = roleModuleActionId;
	}

	public RoleModuleAction(int roleModuleActionId, Integer packageId,
			Integer communityId, Integer roleId, Integer moduleId,
			String fgView, String fgAdd, String fgEdit, String fgDelete,
			Integer modifyBy, Date modyfyDate, Integer createBy, Date createDate) {
		this.roleModuleActionId = roleModuleActionId;
		this.packageId = packageId;
		this.communityId = communityId;
		this.roleId = roleId;
		this.moduleId = moduleId;
		this.fgView = fgView;
		this.fgAdd = fgAdd;
		this.fgEdit = fgEdit;
		this.fgDelete = fgDelete;
		this.modifyBy = modifyBy;
		this.modyfyDate = modyfyDate;
		this.createBy = createBy;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "role_module_action_id", unique = true, nullable = false)
	public int getRoleModuleActionId() {
		return this.roleModuleActionId;
	}

	public void setRoleModuleActionId(int roleModuleActionId) {
		this.roleModuleActionId = roleModuleActionId;
	}

	@Column(name = "package_id")
	public Integer getPackageId() {
		return this.packageId;
	}

	public void setPackageId(Integer packageId) {
		this.packageId = packageId;
	}

	@Column(name = "community_id")
	public Integer getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(Integer communityId) {
		this.communityId = communityId;
	}

	@Column(name = "role_id")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "module_id")
	public Integer getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name = "fg_view", length = 1)
	public String getFgView() {
		return this.fgView;
	}

	public void setFgView(String fgView) {
		this.fgView = fgView;
	}

	@Column(name = "fg_Add", length = 1)
	public String getFgAdd() {
		return this.fgAdd;
	}

	public void setFgAdd(String fgAdd) {
		this.fgAdd = fgAdd;
	}

	@Column(name = "fg_edit", length = 1)
	public String getFgEdit() {
		return this.fgEdit;
	}

	public void setFgEdit(String fgEdit) {
		this.fgEdit = fgEdit;
	}

	@Column(name = "fg_delete", length = 1)
	public String getFgDelete() {
		return this.fgDelete;
	}

	public void setFgDelete(String fgDelete) {
		this.fgDelete = fgDelete;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modyfy_date", length = 19)
	public Date getModyfyDate() {
		return this.modyfyDate;
	}

	public void setModyfyDate(Date modyfyDate) {
		this.modyfyDate = modyfyDate;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
