package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TrnPostReply generated by hbm2java
 */
@Entity
@Table(name = "trn_post_reply", catalog = "haaksquare_db")
public class TrnPostReply implements java.io.Serializable {

	private Long id;
	private long parentId;
	private int communityId;
	private int communityGroup;
	private int masterFlag;
	private int moduleId;
	private int moduleSubId;
	private int languageId;
	private String message;
	private String imageUrl;
	private String clipUrl;
	private String macIpAddress;
	private int createBy;
	private Date createDate;
	private int isDelete;

	public TrnPostReply() {
	}

	public TrnPostReply(long parentId, int communityId, int communityGroup,
			int masterFlag, int moduleId, int moduleSubId, int languageId,
			String message, int createBy, Date createDate, int isDelete) {
		this.parentId = parentId;
		this.communityId = communityId;
		this.communityGroup = communityGroup;
		this.masterFlag = masterFlag;
		this.moduleId = moduleId;
		this.moduleSubId = moduleSubId;
		this.languageId = languageId;
		this.message = message;
		this.createBy = createBy;
		this.createDate = createDate;
		this.isDelete = isDelete;
	}

	public TrnPostReply(long parentId, int communityId, int communityGroup,
			int masterFlag, int moduleId, int moduleSubId, int languageId,
			String message, String imageUrl, String clipUrl,
			String macIpAddress, int createBy, Date createDate, int isDelete) {
		this.parentId = parentId;
		this.communityId = communityId;
		this.communityGroup = communityGroup;
		this.masterFlag = masterFlag;
		this.moduleId = moduleId;
		this.moduleSubId = moduleSubId;
		this.languageId = languageId;
		this.message = message;
		this.imageUrl = imageUrl;
		this.clipUrl = clipUrl;
		this.macIpAddress = macIpAddress;
		this.createBy = createBy;
		this.createDate = createDate;
		this.isDelete = isDelete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "parent_id", nullable = false)
	public long getParentId() {
		return this.parentId;
	}

	public void setParentId(long parentId) {
		this.parentId = parentId;
	}

	@Column(name = "community_id", nullable = false)
	public int getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(int communityId) {
		this.communityId = communityId;
	}

	@Column(name = "community_group", nullable = false)
	public int getCommunityGroup() {
		return this.communityGroup;
	}

	public void setCommunityGroup(int communityGroup) {
		this.communityGroup = communityGroup;
	}

	@Column(name = "master_flag", nullable = false)
	public int getMasterFlag() {
		return this.masterFlag;
	}

	public void setMasterFlag(int masterFlag) {
		this.masterFlag = masterFlag;
	}

	@Column(name = "module_id", nullable = false)
	public int getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(int moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name = "module_sub_id", nullable = false)
	public int getModuleSubId() {
		return this.moduleSubId;
	}

	public void setModuleSubId(int moduleSubId) {
		this.moduleSubId = moduleSubId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	@Column(name = "message", nullable = false, length = 2000)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "image_url", length = 2000)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "clip_url", length = 2000)
	public String getClipUrl() {
		return this.clipUrl;
	}

	public void setClipUrl(String clipUrl) {
		this.clipUrl = clipUrl;
	}

	@Column(name = "MAC_ip_address", length = 100)
	public String getMacIpAddress() {
		return this.macIpAddress;
	}

	public void setMacIpAddress(String macIpAddress) {
		this.macIpAddress = macIpAddress;
	}

	@Column(name = "create_by", nullable = false)
	public int getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(int createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "is_delete", nullable = false)
	public int getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(int isDelete) {
		this.isDelete = isDelete;
	}

}
