package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VBoard generated by hbm2java
 */
@Entity
@Table(name = "v_board", catalog = "haaksquare_db")
public class VBoard implements java.io.Serializable {

	private VBoardId id;

	public VBoard() {
	}

	public VBoard(VBoardId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "firstName", column = @Column(name = "first_name", length = 200)),
			@AttributeOverride(name = "lastName", column = @Column(name = "last_name", length = 200)),
			@AttributeOverride(name = "email", column = @Column(name = "email", length = 200)),
			@AttributeOverride(name = "positionName", column = @Column(name = "position_name", nullable = false, length = 200)),
			@AttributeOverride(name = "positionLevel", column = @Column(name = "position_level", nullable = false)),
			@AttributeOverride(name = "attachSeq", column = @Column(name = "attach_seq", nullable = false)),
			@AttributeOverride(name = "fileTypeId", column = @Column(name = "file_type_id", nullable = false)),
			@AttributeOverride(name = "fileName", column = @Column(name = "file_name", nullable = false, length = 200)),
			@AttributeOverride(name = "pathName", column = @Column(name = "path_name", nullable = false, length = 200)),
			@AttributeOverride(name = "fileDetail", column = @Column(name = "file_detail", nullable = false, length = 2000)),
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)),
			@AttributeOverride(name = "companyName", column = @Column(name = "company_name", length = 500)),
			@AttributeOverride(name = "companyGroupName", column = @Column(name = "company_group_name", length = 500)) })
	public VBoardId getId() {
		return this.id;
	}

	public void setId(VBoardId id) {
		this.id = id;
	}

}
