package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VCommunitySaleRent generated by hbm2java
 */
@Entity
@Table(name = "v_community_sale_rent", catalog = "haaksquare_db")
public class VCommunitySaleRent implements java.io.Serializable {

	private VCommunitySaleRentId id;

	public VCommunitySaleRent() {
	}

	public VCommunitySaleRent(VCommunitySaleRentId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "communitySaleRentId", column = @Column(name = "community_sale_rent_id", nullable = false)),
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)),
			@AttributeOverride(name = "salesRentName", column = @Column(name = "sales_rent_name", length = 100)),
			@AttributeOverride(name = "communityTypeName", column = @Column(name = "community_type_name")),
			@AttributeOverride(name = "valueAmount", column = @Column(name = "value_amount", precision = 10, scale = 0)),
			@AttributeOverride(name = "landSpace", column = @Column(name = "land_space", precision = 10)),
			@AttributeOverride(name = "liveSpace", column = @Column(name = "live_space", precision = 10)),
			@AttributeOverride(name = "bedRoom", column = @Column(name = "bed_room")),
			@AttributeOverride(name = "bathRoom", column = @Column(name = "bath_room")),
			@AttributeOverride(name = "salesRentDetail", column = @Column(name = "sales_rent_detail", length = 1000)),
			@AttributeOverride(name = "exteriorOption", column = @Column(name = "exterior_option", length = 1000)),
			@AttributeOverride(name = "interiorOption", column = @Column(name = "interior_option", length = 1000)),
			@AttributeOverride(name = "contract", column = @Column(name = "contract", length = 1000)),
			@AttributeOverride(name = "fileName", column = @Column(name = "file_name", nullable = false, length = 200)),
			@AttributeOverride(name = "pathName", column = @Column(name = "path_name", nullable = false, length = 200)),
			@AttributeOverride(name = "attachUrl", column = @Column(name = "attach_url", nullable = false, length = 200)),
			@AttributeOverride(name = "salesRentUrl", column = @Column(name = "sales_rent_url", length = 1000)),
			@AttributeOverride(name = "attachSeq", column = @Column(name = "attach_seq", nullable = false)),
			@AttributeOverride(name = "fileDetail", column = @Column(name = "file_detail", nullable = false, length = 2000)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)),
			@AttributeOverride(name = "contractPerson", column = @Column(name = "contract_person", length = 300)),
			@AttributeOverride(name = "contractNumber", column = @Column(name = "contract_number", length = 300)),
			@AttributeOverride(name = "address", column = @Column(name = "address", length = 1000)) })
	public VCommunitySaleRentId getId() {
		return this.id;
	}

	public void setId(VCommunitySaleRentId id) {
		this.id = id;
	}

}
