package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VCommunityDetailId generated by hbm2java
 */
@Embeddable
public class VCommunityDetailId implements java.io.Serializable {

	private int communityId;
	private String communityName;
	private String communitySize;
	private String companyOwner;
	private Long startPrise;
	private Long endPrise;
	private Integer addressId;
	private String addressNo;
	private String soi;
	private String moo;
	private String road;
	private String state;
	private String zipcode;
	private String country;
	private String telephone;
	private String mobile;
	private String communityTypeName;
	private String provinceId;
	private String provinceName;
	private String amphoeName;
	private String tumbolName;
	private String amphoeId;
	private String googleMapLatitude;
	private String googleMapLongtitude;
	private String googleMapUrl;
	private String fileName;
	private String pathName;
	private String fileDetail;
	private String fileTypeName;

	public VCommunityDetailId() {
	}

	public VCommunityDetailId(int communityId, String fileName,
			String pathName, String fileDetail, String fileTypeName) {
		this.communityId = communityId;
		this.fileName = fileName;
		this.pathName = pathName;
		this.fileDetail = fileDetail;
		this.fileTypeName = fileTypeName;
	}

	public VCommunityDetailId(int communityId, String communityName,
			String communitySize, String companyOwner, Long startPrise,
			Long endPrise, Integer addressId, String addressNo, String soi,
			String moo, String road, String state, String zipcode,
			String country, String telephone, String mobile,
			String communityTypeName, String provinceId, String provinceName,
			String amphoeName, String tumbolName, String amphoeId,
			String googleMapLatitude, String googleMapLongtitude,
			String googleMapUrl, String fileName, String pathName,
			String fileDetail, String fileTypeName) {
		this.communityId = communityId;
		this.communityName = communityName;
		this.communitySize = communitySize;
		this.companyOwner = companyOwner;
		this.startPrise = startPrise;
		this.endPrise = endPrise;
		this.addressId = addressId;
		this.addressNo = addressNo;
		this.soi = soi;
		this.moo = moo;
		this.road = road;
		this.state = state;
		this.zipcode = zipcode;
		this.country = country;
		this.telephone = telephone;
		this.mobile = mobile;
		this.communityTypeName = communityTypeName;
		this.provinceId = provinceId;
		this.provinceName = provinceName;
		this.amphoeName = amphoeName;
		this.tumbolName = tumbolName;
		this.amphoeId = amphoeId;
		this.googleMapLatitude = googleMapLatitude;
		this.googleMapLongtitude = googleMapLongtitude;
		this.googleMapUrl = googleMapUrl;
		this.fileName = fileName;
		this.pathName = pathName;
		this.fileDetail = fileDetail;
		this.fileTypeName = fileTypeName;
	}

	@Column(name = "community_id", nullable = false)
	public int getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(int communityId) {
		this.communityId = communityId;
	}

	@Column(name = "community_name", length = 200)
	public String getCommunityName() {
		return this.communityName;
	}

	public void setCommunityName(String communityName) {
		this.communityName = communityName;
	}

	@Column(name = "community_size", length = 100)
	public String getCommunitySize() {
		return this.communitySize;
	}

	public void setCommunitySize(String communitySize) {
		this.communitySize = communitySize;
	}

	@Column(name = "company_owner", length = 200)
	public String getCompanyOwner() {
		return this.companyOwner;
	}

	public void setCompanyOwner(String companyOwner) {
		this.companyOwner = companyOwner;
	}

	@Column(name = "start_prise", precision = 10, scale = 0)
	public Long getStartPrise() {
		return this.startPrise;
	}

	public void setStartPrise(Long startPrise) {
		this.startPrise = startPrise;
	}

	@Column(name = "end_prise", precision = 10, scale = 0)
	public Long getEndPrise() {
		return this.endPrise;
	}

	public void setEndPrise(Long endPrise) {
		this.endPrise = endPrise;
	}

	@Column(name = "address_id")
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@Column(name = "address_no", length = 1000)
	public String getAddressNo() {
		return this.addressNo;
	}

	public void setAddressNo(String addressNo) {
		this.addressNo = addressNo;
	}

	@Column(name = "soi", length = 200)
	public String getSoi() {
		return this.soi;
	}

	public void setSoi(String soi) {
		this.soi = soi;
	}

	@Column(name = "moo", length = 200)
	public String getMoo() {
		return this.moo;
	}

	public void setMoo(String moo) {
		this.moo = moo;
	}

	@Column(name = "road", length = 200)
	public String getRoad() {
		return this.road;
	}

	public void setRoad(String road) {
		this.road = road;
	}

	@Column(name = "state", length = 200)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "zipcode", length = 10)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "country", length = 200)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "telephone", length = 100)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "mobile", length = 100)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "community_type_name")
	public String getCommunityTypeName() {
		return this.communityTypeName;
	}

	public void setCommunityTypeName(String communityTypeName) {
		this.communityTypeName = communityTypeName;
	}

	@Column(name = "province_id", length = 10)
	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

	@Column(name = "province_name")
	public String getProvinceName() {
		return this.provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	@Column(name = "amphoe_name")
	public String getAmphoeName() {
		return this.amphoeName;
	}

	public void setAmphoeName(String amphoeName) {
		this.amphoeName = amphoeName;
	}

	@Column(name = "tumbol_name", length = 100)
	public String getTumbolName() {
		return this.tumbolName;
	}

	public void setTumbolName(String tumbolName) {
		this.tumbolName = tumbolName;
	}

	@Column(name = "amphoe_id", length = 10)
	public String getAmphoeId() {
		return this.amphoeId;
	}

	public void setAmphoeId(String amphoeId) {
		this.amphoeId = amphoeId;
	}

	@Column(name = "google_map_latitude", length = 500)
	public String getGoogleMapLatitude() {
		return this.googleMapLatitude;
	}

	public void setGoogleMapLatitude(String googleMapLatitude) {
		this.googleMapLatitude = googleMapLatitude;
	}

	@Column(name = "google_map_longtitude", length = 500)
	public String getGoogleMapLongtitude() {
		return this.googleMapLongtitude;
	}

	public void setGoogleMapLongtitude(String googleMapLongtitude) {
		this.googleMapLongtitude = googleMapLongtitude;
	}

	@Column(name = "google_map_url", length = 500)
	public String getGoogleMapUrl() {
		return this.googleMapUrl;
	}

	public void setGoogleMapUrl(String googleMapUrl) {
		this.googleMapUrl = googleMapUrl;
	}

	@Column(name = "file_name", nullable = false, length = 200)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "path_name", nullable = false, length = 200)
	public String getPathName() {
		return this.pathName;
	}

	public void setPathName(String pathName) {
		this.pathName = pathName;
	}

	@Column(name = "file_detail", nullable = false, length = 2000)
	public String getFileDetail() {
		return this.fileDetail;
	}

	public void setFileDetail(String fileDetail) {
		this.fileDetail = fileDetail;
	}

	@Column(name = "file_type_name", nullable = false, length = 100)
	public String getFileTypeName() {
		return this.fileTypeName;
	}

	public void setFileTypeName(String fileTypeName) {
		this.fileTypeName = fileTypeName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VCommunityDetailId))
			return false;
		VCommunityDetailId castOther = (VCommunityDetailId) other;

		return (this.getCommunityId() == castOther.getCommunityId())
				&& ((this.getCommunityName() == castOther.getCommunityName()) || (this
						.getCommunityName() != null
						&& castOther.getCommunityName() != null && this
						.getCommunityName()
						.equals(castOther.getCommunityName())))
				&& ((this.getCommunitySize() == castOther.getCommunitySize()) || (this
						.getCommunitySize() != null
						&& castOther.getCommunitySize() != null && this
						.getCommunitySize()
						.equals(castOther.getCommunitySize())))
				&& ((this.getCompanyOwner() == castOther.getCompanyOwner()) || (this
						.getCompanyOwner() != null
						&& castOther.getCompanyOwner() != null && this
						.getCompanyOwner().equals(castOther.getCompanyOwner())))
				&& ((this.getStartPrise() == castOther.getStartPrise()) || (this
						.getStartPrise() != null
						&& castOther.getStartPrise() != null && this
						.getStartPrise().equals(castOther.getStartPrise())))
				&& ((this.getEndPrise() == castOther.getEndPrise()) || (this
						.getEndPrise() != null
						&& castOther.getEndPrise() != null && this
						.getEndPrise().equals(castOther.getEndPrise())))
				&& ((this.getAddressId() == castOther.getAddressId()) || (this
						.getAddressId() != null
						&& castOther.getAddressId() != null && this
						.getAddressId().equals(castOther.getAddressId())))
				&& ((this.getAddressNo() == castOther.getAddressNo()) || (this
						.getAddressNo() != null
						&& castOther.getAddressNo() != null && this
						.getAddressNo().equals(castOther.getAddressNo())))
				&& ((this.getSoi() == castOther.getSoi()) || (this.getSoi() != null
						&& castOther.getSoi() != null && this.getSoi().equals(
						castOther.getSoi())))
				&& ((this.getMoo() == castOther.getMoo()) || (this.getMoo() != null
						&& castOther.getMoo() != null && this.getMoo().equals(
						castOther.getMoo())))
				&& ((this.getRoad() == castOther.getRoad()) || (this.getRoad() != null
						&& castOther.getRoad() != null && this.getRoad()
						.equals(castOther.getRoad())))
				&& ((this.getState() == castOther.getState()) || (this
						.getState() != null && castOther.getState() != null && this
						.getState().equals(castOther.getState())))
				&& ((this.getZipcode() == castOther.getZipcode()) || (this
						.getZipcode() != null && castOther.getZipcode() != null && this
						.getZipcode().equals(castOther.getZipcode())))
				&& ((this.getCountry() == castOther.getCountry()) || (this
						.getCountry() != null && castOther.getCountry() != null && this
						.getCountry().equals(castOther.getCountry())))
				&& ((this.getTelephone() == castOther.getTelephone()) || (this
						.getTelephone() != null
						&& castOther.getTelephone() != null && this
						.getTelephone().equals(castOther.getTelephone())))
				&& ((this.getMobile() == castOther.getMobile()) || (this
						.getMobile() != null && castOther.getMobile() != null && this
						.getMobile().equals(castOther.getMobile())))
				&& ((this.getCommunityTypeName() == castOther
						.getCommunityTypeName()) || (this
						.getCommunityTypeName() != null
						&& castOther.getCommunityTypeName() != null && this
						.getCommunityTypeName().equals(
								castOther.getCommunityTypeName())))
				&& ((this.getProvinceId() == castOther.getProvinceId()) || (this
						.getProvinceId() != null
						&& castOther.getProvinceId() != null && this
						.getProvinceId().equals(castOther.getProvinceId())))
				&& ((this.getProvinceName() == castOther.getProvinceName()) || (this
						.getProvinceName() != null
						&& castOther.getProvinceName() != null && this
						.getProvinceName().equals(castOther.getProvinceName())))
				&& ((this.getAmphoeName() == castOther.getAmphoeName()) || (this
						.getAmphoeName() != null
						&& castOther.getAmphoeName() != null && this
						.getAmphoeName().equals(castOther.getAmphoeName())))
				&& ((this.getTumbolName() == castOther.getTumbolName()) || (this
						.getTumbolName() != null
						&& castOther.getTumbolName() != null && this
						.getTumbolName().equals(castOther.getTumbolName())))
				&& ((this.getAmphoeId() == castOther.getAmphoeId()) || (this
						.getAmphoeId() != null
						&& castOther.getAmphoeId() != null && this
						.getAmphoeId().equals(castOther.getAmphoeId())))
				&& ((this.getGoogleMapLatitude() == castOther
						.getGoogleMapLatitude()) || (this
						.getGoogleMapLatitude() != null
						&& castOther.getGoogleMapLatitude() != null && this
						.getGoogleMapLatitude().equals(
								castOther.getGoogleMapLatitude())))
				&& ((this.getGoogleMapLongtitude() == castOther
						.getGoogleMapLongtitude()) || (this
						.getGoogleMapLongtitude() != null
						&& castOther.getGoogleMapLongtitude() != null && this
						.getGoogleMapLongtitude().equals(
								castOther.getGoogleMapLongtitude())))
				&& ((this.getGoogleMapUrl() == castOther.getGoogleMapUrl()) || (this
						.getGoogleMapUrl() != null
						&& castOther.getGoogleMapUrl() != null && this
						.getGoogleMapUrl().equals(castOther.getGoogleMapUrl())))
				&& ((this.getFileName() == castOther.getFileName()) || (this
						.getFileName() != null
						&& castOther.getFileName() != null && this
						.getFileName().equals(castOther.getFileName())))
				&& ((this.getPathName() == castOther.getPathName()) || (this
						.getPathName() != null
						&& castOther.getPathName() != null && this
						.getPathName().equals(castOther.getPathName())))
				&& ((this.getFileDetail() == castOther.getFileDetail()) || (this
						.getFileDetail() != null
						&& castOther.getFileDetail() != null && this
						.getFileDetail().equals(castOther.getFileDetail())))
				&& ((this.getFileTypeName() == castOther.getFileTypeName()) || (this
						.getFileTypeName() != null
						&& castOther.getFileTypeName() != null && this
						.getFileTypeName().equals(castOther.getFileTypeName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCommunityId();
		result = 37
				* result
				+ (getCommunityName() == null ? 0 : this.getCommunityName()
						.hashCode());
		result = 37
				* result
				+ (getCommunitySize() == null ? 0 : this.getCommunitySize()
						.hashCode());
		result = 37
				* result
				+ (getCompanyOwner() == null ? 0 : this.getCompanyOwner()
						.hashCode());
		result = 37
				* result
				+ (getStartPrise() == null ? 0 : this.getStartPrise()
						.hashCode());
		result = 37 * result
				+ (getEndPrise() == null ? 0 : this.getEndPrise().hashCode());
		result = 37 * result
				+ (getAddressId() == null ? 0 : this.getAddressId().hashCode());
		result = 37 * result
				+ (getAddressNo() == null ? 0 : this.getAddressNo().hashCode());
		result = 37 * result
				+ (getSoi() == null ? 0 : this.getSoi().hashCode());
		result = 37 * result
				+ (getMoo() == null ? 0 : this.getMoo().hashCode());
		result = 37 * result
				+ (getRoad() == null ? 0 : this.getRoad().hashCode());
		result = 37 * result
				+ (getState() == null ? 0 : this.getState().hashCode());
		result = 37 * result
				+ (getZipcode() == null ? 0 : this.getZipcode().hashCode());
		result = 37 * result
				+ (getCountry() == null ? 0 : this.getCountry().hashCode());
		result = 37 * result
				+ (getTelephone() == null ? 0 : this.getTelephone().hashCode());
		result = 37 * result
				+ (getMobile() == null ? 0 : this.getMobile().hashCode());
		result = 37
				* result
				+ (getCommunityTypeName() == null ? 0 : this
						.getCommunityTypeName().hashCode());
		result = 37
				* result
				+ (getProvinceId() == null ? 0 : this.getProvinceId()
						.hashCode());
		result = 37
				* result
				+ (getProvinceName() == null ? 0 : this.getProvinceName()
						.hashCode());
		result = 37
				* result
				+ (getAmphoeName() == null ? 0 : this.getAmphoeName()
						.hashCode());
		result = 37
				* result
				+ (getTumbolName() == null ? 0 : this.getTumbolName()
						.hashCode());
		result = 37 * result
				+ (getAmphoeId() == null ? 0 : this.getAmphoeId().hashCode());
		result = 37
				* result
				+ (getGoogleMapLatitude() == null ? 0 : this
						.getGoogleMapLatitude().hashCode());
		result = 37
				* result
				+ (getGoogleMapLongtitude() == null ? 0 : this
						.getGoogleMapLongtitude().hashCode());
		result = 37
				* result
				+ (getGoogleMapUrl() == null ? 0 : this.getGoogleMapUrl()
						.hashCode());
		result = 37 * result
				+ (getFileName() == null ? 0 : this.getFileName().hashCode());
		result = 37 * result
				+ (getPathName() == null ? 0 : this.getPathName().hashCode());
		result = 37
				* result
				+ (getFileDetail() == null ? 0 : this.getFileDetail()
						.hashCode());
		result = 37
				* result
				+ (getFileTypeName() == null ? 0 : this.getFileTypeName()
						.hashCode());
		return result;
	}

}
