package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VCommnunityOpportunities generated by hbm2java
 */
@Entity
@Table(name = "v_commnunity_opportunities", catalog = "haaksquare_db")
public class VCommnunityOpportunities implements java.io.Serializable {

	private VCommnunityOpportunitiesId id;

	public VCommnunityOpportunities() {
	}

	public VCommnunityOpportunities(VCommnunityOpportunitiesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "oppCategoryId", column = @Column(name = "opp_category_id")),
			@AttributeOverride(name = "oppSubCategoryId", column = @Column(name = "opp_sub_category_id")),
			@AttributeOverride(name = "communityOppId", column = @Column(name = "community_opp_id", nullable = false)),
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)),
			@AttributeOverride(name = "oppSeq", column = @Column(name = "opp_seq", nullable = false)),
			@AttributeOverride(name = "fgPublic", column = @Column(name = "fg_public", length = 1)),
			@AttributeOverride(name = "oppDetail", column = @Column(name = "opp_detail", length = 2000)),
			@AttributeOverride(name = "oppContact", column = @Column(name = "opp_contact", length = 500)),
			@AttributeOverride(name = "oppLink", column = @Column(name = "opp_link", length = 300)),
			@AttributeOverride(name = "oppUrl", column = @Column(name = "opp_url", length = 1000)),
			@AttributeOverride(name = "oppGoogleMap", column = @Column(name = "opp_google_map", length = 1000)),
			@AttributeOverride(name = "googleMapLatitude", column = @Column(name = "google_map_latitude", length = 500)),
			@AttributeOverride(name = "googleMapLongtitude", column = @Column(name = "google_map_longtitude", length = 500)),
			@AttributeOverride(name = "googleMapUrl", column = @Column(name = "google_map_url", length = 500)),
			@AttributeOverride(name = "oppCategoryName", column = @Column(name = "opp_category_name", length = 100)),
			@AttributeOverride(name = "oppSubCategoryName", column = @Column(name = "opp_sub_category_name", length = 100)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)),
			@AttributeOverride(name = "modifyDate", column = @Column(name = "modify_date", length = 19)),
			@AttributeOverride(name = "createBy", column = @Column(name = "create_by")),
			@AttributeOverride(name = "createDate", column = @Column(name = "create_date", length = 10)),
			@AttributeOverride(name = "modifyBy", column = @Column(name = "modify_by")) })
	public VCommnunityOpportunitiesId getId() {
		return this.id;
	}

	public void setId(VCommnunityOpportunitiesId id) {
		this.id = id;
	}

}
