package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VCommunityAbout generated by hbm2java
 */
@Entity
@Table(name = "v_community_about", catalog = "haaksquare_db")
public class VCommunityAbout implements java.io.Serializable {

	private VCommunityAboutId id;

	public VCommunityAbout() {
	}

	public VCommunityAbout(VCommunityAboutId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)),
			@AttributeOverride(name = "communityName", column = @Column(name = "community_name", length = 200)),
			@AttributeOverride(name = "communityTypeName", column = @Column(name = "community_type_name")),
			@AttributeOverride(name = "provinceName", column = @Column(name = "province_name")),
			@AttributeOverride(name = "amphoeName", column = @Column(name = "amphoe_name")),
			@AttributeOverride(name = "tumbolName", column = @Column(name = "tumbol_name", length = 100)),
			@AttributeOverride(name = "fileName", column = @Column(name = "file_name", nullable = false, length = 200)),
			@AttributeOverride(name = "fileTypeName", column = @Column(name = "file_type_name", nullable = false, length = 100)),
			@AttributeOverride(name = "pathName", column = @Column(name = "path_name", nullable = false, length = 200)),
			@AttributeOverride(name = "googleMapLatitude", column = @Column(name = "google_map_latitude", length = 500)),
			@AttributeOverride(name = "googleMapLongtitude", column = @Column(name = "google_map_longtitude", length = 500)),
			@AttributeOverride(name = "communityShotDetail", column = @Column(name = "community_shot_detail", length = 1000)) })
	public VCommunityAboutId getId() {
		return this.id;
	}

	public void setId(VCommunityAboutId id) {
		this.id = id;
	}

}
