package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VCommunity generated by hbm2java
 */
@Entity
@Table(name = "v_community", catalog = "haaksquare_db")
public class VCommunity implements java.io.Serializable {

	private VCommunityId id;

	public VCommunity() {
	}

	public VCommunity(VCommunityId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)),
			@AttributeOverride(name = "communityName", column = @Column(name = "community_name", length = 200)),
			@AttributeOverride(name = "communityTypeName", column = @Column(name = "community_type_name")),
			@AttributeOverride(name = "provinceName", column = @Column(name = "province_name")),
			@AttributeOverride(name = "amphoeName", column = @Column(name = "amphoe_name")),
			@AttributeOverride(name = "tumbolName", column = @Column(name = "tumbol_name", length = 100)),
			@AttributeOverride(name = "googleMapLatitude", column = @Column(name = "google_map_latitude", length = 500)),
			@AttributeOverride(name = "googleMapLongtitude", column = @Column(name = "google_map_longtitude", length = 500)),
			@AttributeOverride(name = "googleMapUrl", column = @Column(name = "google_map_url", length = 500)),
			@AttributeOverride(name = "communityShotDetail", column = @Column(name = "community_shot_detail", length = 1000)),
			@AttributeOverride(name = "packageId", column = @Column(name = "package_id")),
			@AttributeOverride(name = "fileName", column = @Column(name = "file_name", nullable = false, length = 200)),
			@AttributeOverride(name = "pathName", column = @Column(name = "path_name", nullable = false, length = 200)),
			@AttributeOverride(name = "fileTypeId", column = @Column(name = "file_type_id", nullable = false)),
			@AttributeOverride(name = "communitySize", column = @Column(name = "community_size", length = 100)),
			@AttributeOverride(name = "communityDetail", column = @Column(name = "community_detail", length = 2000)),
			@AttributeOverride(name = "companyOwner", column = @Column(name = "company_owner", length = 200)),
			@AttributeOverride(name = "startPrise", column = @Column(name = "start_prise", precision = 10, scale = 0)),
			@AttributeOverride(name = "endPrise", column = @Column(name = "end_prise", precision = 10, scale = 0)),
			@AttributeOverride(name = "addressId", column = @Column(name = "address_id")),
			@AttributeOverride(name = "addressNo", column = @Column(name = "address_no", length = 1000)),
			@AttributeOverride(name = "soi", column = @Column(name = "soi", length = 200)),
			@AttributeOverride(name = "moo", column = @Column(name = "moo", length = 200)),
			@AttributeOverride(name = "road", column = @Column(name = "road", length = 200)),
			@AttributeOverride(name = "state", column = @Column(name = "state", length = 200)),
			@AttributeOverride(name = "zipcode", column = @Column(name = "zipcode", length = 10)),
			@AttributeOverride(name = "country", column = @Column(name = "country", length = 200)),
			@AttributeOverride(name = "telephone", column = @Column(name = "telephone", length = 100)),
			@AttributeOverride(name = "mobile", column = @Column(name = "mobile", length = 100)),
			@AttributeOverride(name = "unitAll", column = @Column(name = "unit_all")),
			@AttributeOverride(name = "unitLive", column = @Column(name = "unit_live")),
			@AttributeOverride(name = "unitSales", column = @Column(name = "unit_sales")),
			@AttributeOverride(name = "unitResidence", column = @Column(name = "unit_residence")),
			@AttributeOverride(name = "cat", column = @Column(name = "cat")),
			@AttributeOverride(name = "dog", column = @Column(name = "dog")),
			@AttributeOverride(name = "contractorsNo", column = @Column(name = "contractors_no")),
			@AttributeOverride(name = "contractorsEmployeesNo", column = @Column(name = "Contractors_employees_no")),
			@AttributeOverride(name = "fgOpen", column = @Column(name = "fg_open", length = 1)) })
	public VCommunityId getId() {
		return this.id;
	}

	public void setId(VCommunityId id) {
		this.id = id;
	}

}
