package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VCommunityAttachFile generated by hbm2java
 */
@Entity
@Table(name = "v_community_attach_file", catalog = "haaksquare_db")
public class VCommunityAttachFile implements java.io.Serializable {

	private VCommunityAttachFileId id;

	public VCommunityAttachFile() {
	}

	public VCommunityAttachFile(VCommunityAttachFileId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "fileName", column = @Column(name = "file_name", nullable = false, length = 200)),
			@AttributeOverride(name = "fileTypeName", column = @Column(name = "file_type_name", nullable = false, length = 100)),
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)) })
	public VCommunityAttachFileId getId() {
		return this.id;
	}

	public void setId(VCommunityAttachFileId id) {
		this.id = id;
	}

}
