package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VCommunityContractNumber generated by hbm2java
 */
@Entity
@Table(name = "v_community_contract_number", catalog = "haaksquare_db")
public class VCommunityContractNumber implements java.io.Serializable {

	private VCommunityContractNumberId id;

	public VCommunityContractNumber() {
	}

	public VCommunityContractNumber(VCommunityContractNumberId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "contractNumberId", column = @Column(name = "contract_number_id", nullable = false)),
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)),
			@AttributeOverride(name = "contractNumberCategoryId", column = @Column(name = "contract_number_category_id")),
			@AttributeOverride(name = "contractNumberName", column = @Column(name = "contract_number_name", length = 300)),
			@AttributeOverride(name = "contractNumberDetail", column = @Column(name = "contract_number_detail", length = 500)),
			@AttributeOverride(name = "modifyDate", column = @Column(name = "modify_date", length = 19)),
			@AttributeOverride(name = "createBy", column = @Column(name = "create_by")),
			@AttributeOverride(name = "createDate", column = @Column(name = "create_date", length = 10)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)),
			@AttributeOverride(name = "contractNumberCategoryName", column = @Column(name = "contract_number_category_name", length = 100)) })
	public VCommunityContractNumberId getId() {
		return this.id;
	}

	public void setId(VCommunityContractNumberId id) {
		this.id = id;
	}

}
