package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VContractFormSubject generated by hbm2java
 */
@Entity
@Table(name = "v_contract_form_subject", catalog = "haaksquare_db")
public class VContractFormSubject implements java.io.Serializable {

	private VContractFormSubjectId id;

	public VContractFormSubject() {
	}

	public VContractFormSubject(VContractFormSubjectId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "subjectName", column = @Column(name = "subject_name", length = 200)),
			@AttributeOverride(name = "subjectSeq", column = @Column(name = "subject_seq")),
			@AttributeOverride(name = "publicFg", column = @Column(name = "public_fg", length = 1)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", nullable = false, length = 20)),
			@AttributeOverride(name = "firstName", column = @Column(name = "first_name", nullable = false, length = 200)),
			@AttributeOverride(name = "lastName", column = @Column(name = "last_name", length = 200)),
			@AttributeOverride(name = "email", column = @Column(name = "email", length = 100)) })
	public VContractFormSubjectId getId() {
		return this.id;
	}

	public void setId(VContractFormSubjectId id) {
		this.id = id;
	}

}
