package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VMenuNew generated by hbm2java
 */
@Entity
@Table(name = "v_menu_new", catalog = "haaksquare_db")
public class VMenuNew implements java.io.Serializable {

	private VMenuNewId id;

	public VMenuNew() {
	}

	public VMenuNew(VMenuNewId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "menuId", column = @Column(name = "menu_id", nullable = false)),
			@AttributeOverride(name = "menuName", column = @Column(name = "menu_name", length = 100)),
			@AttributeOverride(name = "seq", column = @Column(name = "seq")),
			@AttributeOverride(name = "levelMenu", column = @Column(name = "level_menu")),
			@AttributeOverride(name = "seqSub", column = @Column(name = "seq_sub")),
			@AttributeOverride(name = "parrentSubMenu", column = @Column(name = "parrent_sub_menu")),
			@AttributeOverride(name = "menuUrl", column = @Column(name = "menu_url", nullable = false, length = 100)),
			@AttributeOverride(name = "menuImageUrl", column = @Column(name = "menu_image_url", length = 100)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public VMenuNewId getId() {
		return this.id;
	}

	public void setId(VMenuNewId id) {
		this.id = id;
	}

}
