package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VMenuId generated by hbm2java
 */
@Embeddable
public class VMenuId implements java.io.Serializable {

	private String menuName;
	private String menuUrl;
	private int languageId;
	private String menuImageUrl;
	private int menuId;
	private int packageId;
	private Integer seq;

	public VMenuId() {
	}

	public VMenuId(String menuUrl, int languageId, int menuId, int packageId) {
		this.menuUrl = menuUrl;
		this.languageId = languageId;
		this.menuId = menuId;
		this.packageId = packageId;
	}

	public VMenuId(String menuName, String menuUrl, int languageId,
			String menuImageUrl, int menuId, int packageId, Integer seq) {
		this.menuName = menuName;
		this.menuUrl = menuUrl;
		this.languageId = languageId;
		this.menuImageUrl = menuImageUrl;
		this.menuId = menuId;
		this.packageId = packageId;
		this.seq = seq;
	}

	@Column(name = "menu_name", length = 100)
	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	@Column(name = "menu_url", nullable = false, length = 100)
	public String getMenuUrl() {
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	@Column(name = "menu_image_url", length = 100)
	public String getMenuImageUrl() {
		return this.menuImageUrl;
	}

	public void setMenuImageUrl(String menuImageUrl) {
		this.menuImageUrl = menuImageUrl;
	}

	@Column(name = "menu_id", nullable = false)
	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	@Column(name = "package_id", nullable = false)
	public int getPackageId() {
		return this.packageId;
	}

	public void setPackageId(int packageId) {
		this.packageId = packageId;
	}

	@Column(name = "seq")
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VMenuId))
			return false;
		VMenuId castOther = (VMenuId) other;

		return ((this.getMenuName() == castOther.getMenuName()) || (this
				.getMenuName() != null && castOther.getMenuName() != null && this
				.getMenuName().equals(castOther.getMenuName())))
				&& ((this.getMenuUrl() == castOther.getMenuUrl()) || (this
						.getMenuUrl() != null && castOther.getMenuUrl() != null && this
						.getMenuUrl().equals(castOther.getMenuUrl())))
				&& (this.getLanguageId() == castOther.getLanguageId())
				&& ((this.getMenuImageUrl() == castOther.getMenuImageUrl()) || (this
						.getMenuImageUrl() != null
						&& castOther.getMenuImageUrl() != null && this
						.getMenuImageUrl().equals(castOther.getMenuImageUrl())))
				&& (this.getMenuId() == castOther.getMenuId())
				&& (this.getPackageId() == castOther.getPackageId())
				&& ((this.getSeq() == castOther.getSeq()) || (this.getSeq() != null
						&& castOther.getSeq() != null && this.getSeq().equals(
						castOther.getSeq())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMenuName() == null ? 0 : this.getMenuName().hashCode());
		result = 37 * result
				+ (getMenuUrl() == null ? 0 : this.getMenuUrl().hashCode());
		result = 37 * result + this.getLanguageId();
		result = 37
				* result
				+ (getMenuImageUrl() == null ? 0 : this.getMenuImageUrl()
						.hashCode());
		result = 37 * result + this.getMenuId();
		result = 37 * result + this.getPackageId();
		result = 37 * result
				+ (getSeq() == null ? 0 : this.getSeq().hashCode());
		return result;
	}

}
