package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VResultSendSms generated by hbm2java
 */
@Entity
@Table(name = "v_result_send_sms", catalog = "haaksquare_db")
public class VResultSendSms implements java.io.Serializable {

	private VResultSendSmsId id;

	public VResultSendSms() {
	}

	public VResultSendSms(VResultSendSmsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "smsMessage", column = @Column(name = "sms_message", nullable = false, length = 2000)),
			@AttributeOverride(name = "smsToId", column = @Column(name = "sms_to_id", nullable = false)),
			@AttributeOverride(name = "smsId", column = @Column(name = "sms_id", nullable = false)),
			@AttributeOverride(name = "communityId", column = @Column(name = "community_id", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "mobileNo", column = @Column(name = "mobile_no", nullable = false, length = 20)),
			@AttributeOverride(name = "smsStatus", column = @Column(name = "sms_status", nullable = false, length = 100)),
			@AttributeOverride(name = "smsCradit", column = @Column(name = "sms_cradit", nullable = false)),
			@AttributeOverride(name = "createDate", column = @Column(name = "create_date", nullable = false, length = 10)),
			@AttributeOverride(name = "createBy", column = @Column(name = "create_by", nullable = false)) })
	public VResultSendSmsId getId() {
		return this.id;
	}

	public void setId(VResultSendSmsId id) {
		this.id = id;
	}

}
