package com.haak.haaksq.autogen;

// Generated 11 �.�. 2555, 10:30:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VUserProfileId generated by hbm2java
 */
@Embeddable
public class VUserProfileId implements java.io.Serializable {

	private String mobileNo;
	private int userId;
	private String pass;
	private int communityId;
	private String userName;
	private String firstName;
	private String lastName;
	private String nickName;
	private String email;
	private String sports;
	private String hobbies;
	private String profession;
	private int addressId;
	private Integer createBy;
	private String createDate;
	private String addressNo;
	private Integer noOfCars;
	private Integer noOfDogs;
	private Integer noOfCats;
	private String otherPets;
	private String soi;
	private String moo;
	private String road;
	private String tumbolId;
	private String amphoeId;
	private String provinceId;
	private String state;
	private String zipcode;
	private String country;
	private String tumbolName;
	private String amphoeName;
	private String provinceName;
	private Integer modifyBy;
	private String modifyDate;
	private int languageId;
	private String faxNo;
	private String telephoneNo;

	public VUserProfileId() {
	}

	public VUserProfileId(int userId, String pass, int communityId,
			String userName, String firstName, int addressId, int languageId) {
		this.userId = userId;
		this.pass = pass;
		this.communityId = communityId;
		this.userName = userName;
		this.firstName = firstName;
		this.addressId = addressId;
		this.languageId = languageId;
	}

	public VUserProfileId(String mobileNo, int userId, String pass,
			int communityId, String userName, String firstName,
			String lastName, String nickName, String email, String sports,
			String hobbies, String profession, int addressId, Integer createBy,
			String createDate, String addressNo, Integer noOfCars,
			Integer noOfDogs, Integer noOfCats, String otherPets, String soi,
			String moo, String road, String tumbolId, String amphoeId,
			String provinceId, String state, String zipcode, String country,
			String tumbolName, String amphoeName, String provinceName,
			Integer modifyBy, String modifyDate, int languageId, String faxNo,
			String telephoneNo) {
		this.mobileNo = mobileNo;
		this.userId = userId;
		this.pass = pass;
		this.communityId = communityId;
		this.userName = userName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.nickName = nickName;
		this.email = email;
		this.sports = sports;
		this.hobbies = hobbies;
		this.profession = profession;
		this.addressId = addressId;
		this.createBy = createBy;
		this.createDate = createDate;
		this.addressNo = addressNo;
		this.noOfCars = noOfCars;
		this.noOfDogs = noOfDogs;
		this.noOfCats = noOfCats;
		this.otherPets = otherPets;
		this.soi = soi;
		this.moo = moo;
		this.road = road;
		this.tumbolId = tumbolId;
		this.amphoeId = amphoeId;
		this.provinceId = provinceId;
		this.state = state;
		this.zipcode = zipcode;
		this.country = country;
		this.tumbolName = tumbolName;
		this.amphoeName = amphoeName;
		this.provinceName = provinceName;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.languageId = languageId;
		this.faxNo = faxNo;
		this.telephoneNo = telephoneNo;
	}

	@Column(name = "mobile_no", length = 200)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "pass", nullable = false, length = 10)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "community_id", nullable = false)
	public int getCommunityId() {
		return this.communityId;
	}

	public void setCommunityId(int communityId) {
		this.communityId = communityId;
	}

	@Column(name = "user_name", nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "first_name", nullable = false, length = 200)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 200)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "nick_name", length = 100)
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "sports", length = 200)
	public String getSports() {
		return this.sports;
	}

	public void setSports(String sports) {
		this.sports = sports;
	}

	@Column(name = "hobbies", length = 200)
	public String getHobbies() {
		return this.hobbies;
	}

	public void setHobbies(String hobbies) {
		this.hobbies = hobbies;
	}

	@Column(name = "profession", length = 200)
	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	@Column(name = "address_id", nullable = false)
	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	@Column(name = "create_by")
	public Integer getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Integer createBy) {
		this.createBy = createBy;
	}

	@Column(name = "create_date", length = 170)
	public String getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	@Column(name = "address_no", length = 1000)
	public String getAddressNo() {
		return this.addressNo;
	}

	public void setAddressNo(String addressNo) {
		this.addressNo = addressNo;
	}

	@Column(name = "no_of_cars")
	public Integer getNoOfCars() {
		return this.noOfCars;
	}

	public void setNoOfCars(Integer noOfCars) {
		this.noOfCars = noOfCars;
	}

	@Column(name = "no_of_dogs")
	public Integer getNoOfDogs() {
		return this.noOfDogs;
	}

	public void setNoOfDogs(Integer noOfDogs) {
		this.noOfDogs = noOfDogs;
	}

	@Column(name = "no_of_cats")
	public Integer getNoOfCats() {
		return this.noOfCats;
	}

	public void setNoOfCats(Integer noOfCats) {
		this.noOfCats = noOfCats;
	}

	@Column(name = "other_pets", length = 300)
	public String getOtherPets() {
		return this.otherPets;
	}

	public void setOtherPets(String otherPets) {
		this.otherPets = otherPets;
	}

	@Column(name = "soi", length = 200)
	public String getSoi() {
		return this.soi;
	}

	public void setSoi(String soi) {
		this.soi = soi;
	}

	@Column(name = "moo", length = 200)
	public String getMoo() {
		return this.moo;
	}

	public void setMoo(String moo) {
		this.moo = moo;
	}

	@Column(name = "road", length = 200)
	public String getRoad() {
		return this.road;
	}

	public void setRoad(String road) {
		this.road = road;
	}

	@Column(name = "tumbol_id", length = 10)
	public String getTumbolId() {
		return this.tumbolId;
	}

	public void setTumbolId(String tumbolId) {
		this.tumbolId = tumbolId;
	}

	@Column(name = "amphoe_id", length = 10)
	public String getAmphoeId() {
		return this.amphoeId;
	}

	public void setAmphoeId(String amphoeId) {
		this.amphoeId = amphoeId;
	}

	@Column(name = "province_id", length = 10)
	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

	@Column(name = "state", length = 200)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "zipcode", length = 10)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "country", length = 200)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "tumbol_name", length = 100)
	public String getTumbolName() {
		return this.tumbolName;
	}

	public void setTumbolName(String tumbolName) {
		this.tumbolName = tumbolName;
	}

	@Column(name = "amphoe_name")
	public String getAmphoeName() {
		return this.amphoeName;
	}

	public void setAmphoeName(String amphoeName) {
		this.amphoeName = amphoeName;
	}

	@Column(name = "province_name")
	public String getProvinceName() {
		return this.provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	@Column(name = "modify_by")
	public Integer getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Integer modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Column(name = "modify_date", length = 170)
	public String getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(String modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	@Column(name = "fax_no", length = 200)
	public String getFaxNo() {
		return this.faxNo;
	}

	public void setFaxNo(String faxNo) {
		this.faxNo = faxNo;
	}

	@Column(name = "telephone_no", length = 200)
	public String getTelephoneNo() {
		return this.telephoneNo;
	}

	public void setTelephoneNo(String telephoneNo) {
		this.telephoneNo = telephoneNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VUserProfileId))
			return false;
		VUserProfileId castOther = (VUserProfileId) other;

		return ((this.getMobileNo() == castOther.getMobileNo()) || (this
				.getMobileNo() != null && castOther.getMobileNo() != null && this
				.getMobileNo().equals(castOther.getMobileNo())))
				&& (this.getUserId() == castOther.getUserId())
				&& ((this.getPass() == castOther.getPass()) || (this.getPass() != null
						&& castOther.getPass() != null && this.getPass()
						.equals(castOther.getPass())))
				&& (this.getCommunityId() == castOther.getCommunityId())
				&& ((this.getUserName() == castOther.getUserName()) || (this
						.getUserName() != null
						&& castOther.getUserName() != null && this
						.getUserName().equals(castOther.getUserName())))
				&& ((this.getFirstName() == castOther.getFirstName()) || (this
						.getFirstName() != null
						&& castOther.getFirstName() != null && this
						.getFirstName().equals(castOther.getFirstName())))
				&& ((this.getLastName() == castOther.getLastName()) || (this
						.getLastName() != null
						&& castOther.getLastName() != null && this
						.getLastName().equals(castOther.getLastName())))
				&& ((this.getNickName() == castOther.getNickName()) || (this
						.getNickName() != null
						&& castOther.getNickName() != null && this
						.getNickName().equals(castOther.getNickName())))
				&& ((this.getEmail() == castOther.getEmail()) || (this
						.getEmail() != null && castOther.getEmail() != null && this
						.getEmail().equals(castOther.getEmail())))
				&& ((this.getSports() == castOther.getSports()) || (this
						.getSports() != null && castOther.getSports() != null && this
						.getSports().equals(castOther.getSports())))
				&& ((this.getHobbies() == castOther.getHobbies()) || (this
						.getHobbies() != null && castOther.getHobbies() != null && this
						.getHobbies().equals(castOther.getHobbies())))
				&& ((this.getProfession() == castOther.getProfession()) || (this
						.getProfession() != null
						&& castOther.getProfession() != null && this
						.getProfession().equals(castOther.getProfession())))
				&& (this.getAddressId() == castOther.getAddressId())
				&& ((this.getCreateBy() == castOther.getCreateBy()) || (this
						.getCreateBy() != null
						&& castOther.getCreateBy() != null && this
						.getCreateBy().equals(castOther.getCreateBy())))
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this
						.getCreateDate() != null
						&& castOther.getCreateDate() != null && this
						.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getAddressNo() == castOther.getAddressNo()) || (this
						.getAddressNo() != null
						&& castOther.getAddressNo() != null && this
						.getAddressNo().equals(castOther.getAddressNo())))
				&& ((this.getNoOfCars() == castOther.getNoOfCars()) || (this
						.getNoOfCars() != null
						&& castOther.getNoOfCars() != null && this
						.getNoOfCars().equals(castOther.getNoOfCars())))
				&& ((this.getNoOfDogs() == castOther.getNoOfDogs()) || (this
						.getNoOfDogs() != null
						&& castOther.getNoOfDogs() != null && this
						.getNoOfDogs().equals(castOther.getNoOfDogs())))
				&& ((this.getNoOfCats() == castOther.getNoOfCats()) || (this
						.getNoOfCats() != null
						&& castOther.getNoOfCats() != null && this
						.getNoOfCats().equals(castOther.getNoOfCats())))
				&& ((this.getOtherPets() == castOther.getOtherPets()) || (this
						.getOtherPets() != null
						&& castOther.getOtherPets() != null && this
						.getOtherPets().equals(castOther.getOtherPets())))
				&& ((this.getSoi() == castOther.getSoi()) || (this.getSoi() != null
						&& castOther.getSoi() != null && this.getSoi().equals(
						castOther.getSoi())))
				&& ((this.getMoo() == castOther.getMoo()) || (this.getMoo() != null
						&& castOther.getMoo() != null && this.getMoo().equals(
						castOther.getMoo())))
				&& ((this.getRoad() == castOther.getRoad()) || (this.getRoad() != null
						&& castOther.getRoad() != null && this.getRoad()
						.equals(castOther.getRoad())))
				&& ((this.getTumbolId() == castOther.getTumbolId()) || (this
						.getTumbolId() != null
						&& castOther.getTumbolId() != null && this
						.getTumbolId().equals(castOther.getTumbolId())))
				&& ((this.getAmphoeId() == castOther.getAmphoeId()) || (this
						.getAmphoeId() != null
						&& castOther.getAmphoeId() != null && this
						.getAmphoeId().equals(castOther.getAmphoeId())))
				&& ((this.getProvinceId() == castOther.getProvinceId()) || (this
						.getProvinceId() != null
						&& castOther.getProvinceId() != null && this
						.getProvinceId().equals(castOther.getProvinceId())))
				&& ((this.getState() == castOther.getState()) || (this
						.getState() != null && castOther.getState() != null && this
						.getState().equals(castOther.getState())))
				&& ((this.getZipcode() == castOther.getZipcode()) || (this
						.getZipcode() != null && castOther.getZipcode() != null && this
						.getZipcode().equals(castOther.getZipcode())))
				&& ((this.getCountry() == castOther.getCountry()) || (this
						.getCountry() != null && castOther.getCountry() != null && this
						.getCountry().equals(castOther.getCountry())))
				&& ((this.getTumbolName() == castOther.getTumbolName()) || (this
						.getTumbolName() != null
						&& castOther.getTumbolName() != null && this
						.getTumbolName().equals(castOther.getTumbolName())))
				&& ((this.getAmphoeName() == castOther.getAmphoeName()) || (this
						.getAmphoeName() != null
						&& castOther.getAmphoeName() != null && this
						.getAmphoeName().equals(castOther.getAmphoeName())))
				&& ((this.getProvinceName() == castOther.getProvinceName()) || (this
						.getProvinceName() != null
						&& castOther.getProvinceName() != null && this
						.getProvinceName().equals(castOther.getProvinceName())))
				&& ((this.getModifyBy() == castOther.getModifyBy()) || (this
						.getModifyBy() != null
						&& castOther.getModifyBy() != null && this
						.getModifyBy().equals(castOther.getModifyBy())))
				&& ((this.getModifyDate() == castOther.getModifyDate()) || (this
						.getModifyDate() != null
						&& castOther.getModifyDate() != null && this
						.getModifyDate().equals(castOther.getModifyDate())))
				&& (this.getLanguageId() == castOther.getLanguageId())
				&& ((this.getFaxNo() == castOther.getFaxNo()) || (this
						.getFaxNo() != null && castOther.getFaxNo() != null && this
						.getFaxNo().equals(castOther.getFaxNo())))
				&& ((this.getTelephoneNo() == castOther.getTelephoneNo()) || (this
						.getTelephoneNo() != null
						&& castOther.getTelephoneNo() != null && this
						.getTelephoneNo().equals(castOther.getTelephoneNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMobileNo() == null ? 0 : this.getMobileNo().hashCode());
		result = 37 * result + this.getUserId();
		result = 37 * result
				+ (getPass() == null ? 0 : this.getPass().hashCode());
		result = 37 * result + this.getCommunityId();
		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result
				+ (getFirstName() == null ? 0 : this.getFirstName().hashCode());
		result = 37 * result
				+ (getLastName() == null ? 0 : this.getLastName().hashCode());
		result = 37 * result
				+ (getNickName() == null ? 0 : this.getNickName().hashCode());
		result = 37 * result
				+ (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result
				+ (getSports() == null ? 0 : this.getSports().hashCode());
		result = 37 * result
				+ (getHobbies() == null ? 0 : this.getHobbies().hashCode());
		result = 37
				* result
				+ (getProfession() == null ? 0 : this.getProfession()
						.hashCode());
		result = 37 * result + this.getAddressId();
		result = 37 * result
				+ (getCreateBy() == null ? 0 : this.getCreateBy().hashCode());
		result = 37
				* result
				+ (getCreateDate() == null ? 0 : this.getCreateDate()
						.hashCode());
		result = 37 * result
				+ (getAddressNo() == null ? 0 : this.getAddressNo().hashCode());
		result = 37 * result
				+ (getNoOfCars() == null ? 0 : this.getNoOfCars().hashCode());
		result = 37 * result
				+ (getNoOfDogs() == null ? 0 : this.getNoOfDogs().hashCode());
		result = 37 * result
				+ (getNoOfCats() == null ? 0 : this.getNoOfCats().hashCode());
		result = 37 * result
				+ (getOtherPets() == null ? 0 : this.getOtherPets().hashCode());
		result = 37 * result
				+ (getSoi() == null ? 0 : this.getSoi().hashCode());
		result = 37 * result
				+ (getMoo() == null ? 0 : this.getMoo().hashCode());
		result = 37 * result
				+ (getRoad() == null ? 0 : this.getRoad().hashCode());
		result = 37 * result
				+ (getTumbolId() == null ? 0 : this.getTumbolId().hashCode());
		result = 37 * result
				+ (getAmphoeId() == null ? 0 : this.getAmphoeId().hashCode());
		result = 37
				* result
				+ (getProvinceId() == null ? 0 : this.getProvinceId()
						.hashCode());
		result = 37 * result
				+ (getState() == null ? 0 : this.getState().hashCode());
		result = 37 * result
				+ (getZipcode() == null ? 0 : this.getZipcode().hashCode());
		result = 37 * result
				+ (getCountry() == null ? 0 : this.getCountry().hashCode());
		result = 37
				* result
				+ (getTumbolName() == null ? 0 : this.getTumbolName()
						.hashCode());
		result = 37
				* result
				+ (getAmphoeName() == null ? 0 : this.getAmphoeName()
						.hashCode());
		result = 37
				* result
				+ (getProvinceName() == null ? 0 : this.getProvinceName()
						.hashCode());
		result = 37 * result
				+ (getModifyBy() == null ? 0 : this.getModifyBy().hashCode());
		result = 37
				* result
				+ (getModifyDate() == null ? 0 : this.getModifyDate()
						.hashCode());
		result = 37 * result + this.getLanguageId();
		result = 37 * result
				+ (getFaxNo() == null ? 0 : this.getFaxNo().hashCode());
		result = 37
				* result
				+ (getTelephoneNo() == null ? 0 : this.getTelephoneNo()
						.hashCode());
		return result;
	}

}
